Repository milvus-io/pymilvus, pull requests merged in 2020-12, with the labels that each got.

#373 Fix Wrong description in 'search_in_segment' method
  CHANGELOG.md
  milvus/client/stub.py
Labels: PR | automerge, bug, documentation

#375 Raise exception when inserted entities fields mismatch that at server endpoint
  CHANGELOG.md
  milvus/client/prepare.py
  tests/test_insert.py
Labels: PR | automerge

#362 Test add
  .github/workflows/ci.yml
  .mergify/config.yml
  CHANGELOG.md
  doc/source/tutorial.rst
  tests/conftest.py
  tests/factorys.py
  tests/test_compact.py
  tests/test_flush.py
  tests/test_get_entity_by_id.py
  tests/test_index.py
  tests/test_info.py
  tests/test_insert.py
  tests/test_partition.py
  tests/test_search.py
Labels: PR | automerge

#382 [skip ci] Update api description
  doc/source/api.rst
Labels: PR | automerge, documentation

#385 Remove status in proto
  .gitignore
  CHANGELOG.md
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/gen/status_pb2.py
  grpc-proto/gen/status_pb2_grpc.py
  grpc-proto/milvus.proto
  grpc-proto/python_gen.sh
  grpc-proto/status.proto
  milvus/client/grpc_client/grpc_gen/__init__.py
  milvus/client/grpc_client/grpc_gen/milvus_pb2.py
  milvus/client/grpc_client/grpc_gen/milvus_pb2_grpc.py
  milvus/client/grpc_client/grpc_gen/status_pb2.py
  milvus/client/grpc_client/grpc_gen/status_pb2_grpc.py
  milvus/client/utils.py
Labels: PR | automerge, enhancement

#388 [skip ci] update api description.
  doc/source/api.rst
Labels: documentation

#391 Fix "too many values to unpack" if pool parameter is set to "QueuePool"
  CHANGELOG.md
  milvus/client/pool.py
  tests/test_mix.py
Labels: Issue | Bug, PR | automerge, PR | trigger CI

#393 update github action behaviour
  .github/workflows/ci.yml
  .mergify/config.yml
Labels: PR | automerge, PR | ignore CI

#395 [ci] Optimize search result object to improve performance during loop
  .github/workflows/lint.yml
  CHANGELOG.md
  milvus/__init__.py
  milvus/client/grpc_client/grpc_gen/__init__.py
  milvus/client/grpc_client/grpc_results.py
  milvus/utils.py
  pylint.conf
Labels: PR | automerge, PR | trigger CI, enhancement

#396 Modify mergify strategy
  .mergify/config.yml
Labels: PR | automerge, PR | ignore CI, enhancement
