Repository milvus-io/pymilvus, pull requests merged in 2020-10, with the labels that each got.

#320 Support auto merge PR after reviewed (fix #319)
  .mergify/config.yml
  CHANGELOG.md
Labels: dependencies, enhancement, feature

#322 grammar and build from source
  doc/source/install.rst
Labels: automerge

#321 fix doc error
  doc/source/res/tutorial.md
  doc/source/tutorial.rst
Labels: automerge

#323 change the doc style
  doc/source/res/tutorial.md
Labels: automerge

#324 Overall
  doc/source/conf.py
  doc/source/index.rst
  doc/source/install.rst
Labels: automerge

#325 Add chapter About and Changes
  CHANGELOG.md
  doc/source/about.rst
  doc/source/api.rst
  doc/source/changes.rst
  doc/source/res/about_documentation.md
  doc/source/res/chang_log.md
Labels: automerge, documentation, enhancement

#326 Faq
  CHANGELOG.md
  doc/source/contribute.rst
  doc/source/faq.rst
  doc/source/res/about_documentation.md
Labels: automerge

#327 fix API documentation link
  README.md
Labels: automerge

#329 change the index doc
  doc/source/res/Intro_to_Indexes.md
Labels: automerge

#330 fix index doc error
  doc/source/res/Intro_to_Indexes.md
Labels: automerge

#331 Overall check
  doc/source/changes.rst
  doc/source/conf.py
  doc/source/index.rst
  doc/source/install.rst
  doc/source/res/tutorial.md
  doc/source/tutorial.rst
  requirements.txt
Labels: automerge

#332 fix requirements bug
  requirements.txt
Labels: automerge

#334 Overall check
  README.md
  doc/source/_templates/layout.html
  doc/source/contribute.rst
  doc/source/index.rst
  doc/source/install.rst
  doc/source/param.rst
  doc/source/res/Intro_to_Indexes.md
  doc/source/res/about_documentation.md
  doc/source/res/chang_log.md
  doc/source/tutorial.rst
  requirements.txt
Labels: automerge

#335 Update query chapter
  doc/source/res/query.md
Labels: automerge, documentation

#338 add complex query dsl
  doc/source/about.rst
  doc/source/api.rst
  doc/source/changes.rst
  doc/source/conf.py
  doc/source/contribute.rst
  doc/source/faq.rst
  doc/source/index.rst
  doc/source/install.rst
  doc/source/param.rst
  doc/source/query.rst
  doc/source/res/query.md
  doc/source/results.rst
  doc/source/tutorial.rst
Labels: automerge
