Repository milvus-io/pymilvus, pull requests merged in 2020-11, with the labels that each got.

#340 Update readme
  README.md
Labels: PR | cherry-pick, automerge

#341 Update readme (#340)
  README.md
Labels: automerge

#342 Change method insert to bulk_insert
  .github/workflows/htmlpublish.yml
  .github/workflows/lint.yml
  .mergify/config.yml
  CHANGELOG.md
  conftest.py
  doc/source/api.rst
  doc/source/conf.py
  doc/source/res/chang_log.md
  doc/source/tutorial.rst
  examples/example.py
  examples/example_async.py
  examples/example_index.py
  milvus/__init__.py
  milvus/client/abs_client.py
  milvus/client/abstract.py
  milvus/client/asynch.py
  milvus/client/check.py
  milvus/client/exceptions.py
  milvus/client/grpc_handler.py
  milvus/client/http_handler.py
  milvus/client/pool.py
  milvus/client/prepare.py
  milvus/client/stub.py
  milvus/client/utils.py
  pylint.conf
  setup.py
  tests/conftest.py
  tests/factorys.py
  tests/test_bulk_insert.py
  tests/test_collection.py
  tests/test_index.py
  tests/test_insert.py
  tests/test_partition.py
  tests/test_ping.py
  tests/test_pool.py
  tests/test_search.py
  tests/test_segment.py
  tests/test_task.py
  tests/test_thread.py
  tests/test_utils.py
  tests/test_vectors.py
Labels: automerge, enhancement

#348 New method insert()
  CHANGELOG.md
  doc/source/contribute.rst
  doc/source/tutorial.rst
  examples/example.py
  examples/example_async.py
  milvus/client/__init__.py
  milvus/client/abs_client.py
  milvus/client/abstract.py
  milvus/client/grpc_handler.py
  milvus/client/prepare.py
  milvus/client/stub.py
  pylint.conf
  tests/factorys.py
  tests/test_bulk_insert.py
  tests/test_insert.py
Labels: automerge, feature

#351 fix tutorial doc but
  doc/source/tutorial.rst
Labels: automerge, documentation

#354 Add Ci test in GitHub action
  .github/scripts/server/milvus.yaml
  .github/scripts/server/server.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .mergify/config.yml
  CHANGELOG.md
  doc/source/contribute.rst
Labels: automerge, documentation, feature

#356 fix class `Entity.__str__` func
  milvus/client/abstract.py
Labels: automerge, bug

#358 Add test
  tests/conftest.py
  tests/test_collection.py
  tests/test_delete_entity_by_id.py
  tests/test_index.py
  tests/test_insert.py
  tests/test_partition.py
  tests/test_search.py
Labels: automerge

#360 Example binary
  CHANGELOG.md
  doc/source/api.rst
  doc/source/res/Intro_to_Indexes.md
  doc/source/tutorial.rst
  examples/example.py
  examples/example_async.py
  examples/example_binary.py
  examples/example_index.py
Labels: automerge

#369 Fix index doc wrong example and description (fix #368)
  CHANGELOG.md
  doc/source/res/Intro_to_Indexes.md
Labels: PR | automerge, bug, documentation

#370 [skip ci] Updated api.rst
  doc/source/api.rst
Labels: PR | automerge, documentation

#364 Add encoding utf-8 (#363)
  examples/example_index.py
Labels: PR | automerge, bug
