Repository milvus-io/pymilvus, pull requests merged in 2021-04, with the labels that each got.

#477 Add author info in setup.py
  setup.py
Labels: PR | automerge, PR | cherry-pick

#479 Fix GitHub Actions and update README
  .github/workflows/package.yml
  README.md
Labels: PR | automerge, PR | ignore CI

#491 Update support versions
  milvus/client/pool.py
Labels: PR | automerge, PR | ignore CI

#497 Force using http/https scheme with http-handler
  milvus/client/http_handler.py
Labels: PR | automerge, PR | ignore CI

#498 Bump jinja2 pygments and py
  requirements.txt
Labels: PR | cherry-pick

#500 Prepare for Release 1.1
  CHANGELOG.md
  README.md
  docs/source/conf.py
  docs/source/install.rst
  docs/source/tutorial.rst
Labels: enhancement
