Repository milvus-io/pymilvus, pull requests merged in 2021-05, with the labels that each got.

#504 Remove git dep in setup.py
  setup.py
Labels: Issue | Bug, PR | automerge, PR | ignore CI

#518 Add packaging for master branch
  .github/workflows/package.yml
  .gitignore
  pyproject.toml
  setup.py
Labels: PR | ignore CI

#523 Control required version for grpcio and grpcio-tools
  setup.py
Labels: approved, lgtm

#522 Control required version for grpcio and grpcio-tools
  setup.py
Labels: PR | automerge, PR | ignore CI, approved, lgtm

#525 Copy search params to avoid changing the passed params
  milvus/client/prepare.py
Labels: approved, lgtm, size/XS

#526 Update proto
  grpc-proto/common.proto
  grpc-proto/gen/common_pb2.py
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/gen/schema_pb2.py
  grpc-proto/milvus.proto
  grpc-proto/schema.proto
  milvus/client/grpc_handler.py
  milvus/client/prepare.py
  milvus/client/stub.py
  milvus/grpc_gen/common_pb2.py
  milvus/grpc_gen/milvus_pb2.py
  milvus/grpc_gen/milvus_pb2_grpc.py
  milvus/grpc_gen/schema_pb2.py
Labels: approved, lgtm, size/XXL

#527 Add get method
  milvus/client/grpc_handler.py
  milvus/client/prepare.py
  milvus/client/stub.py
Labels: approved, lgtm, size/S

#529 Prepare to release v1.1.1
  CHANGELOG.md
  OWNERS
  README.md
  setup.py
Labels: lgtm, size/M

#531 Prepare to release v1.1.1 (#529)
  CHANGELOG.md
  README.md
Labels: approved, lgtm, size/S

#530 Change recommended version of pymilvus to 1.1.1
  README.md
Labels: approved, lgtm, size/XS

#533 Change partition_tag to partition_name
  milvus/client/abs_client.py
  milvus/client/check.py
  milvus/client/grpc_handler.py
  milvus/client/http_handler.py
  milvus/client/prepare.py
  milvus/client/stub.py
  tests/test_bulk_insert.py
  tests/test_insert.py
  tests/test_load_partitions.py
  tests/test_partition.py
  tests/test_search.py
Labels: approved, ci-passed, lgtm, size/L
