Repository milvus-io/pymilvus, pull requests merged in 2021-06, with the labels that each got.

#534 Update the docstring of get API
  milvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/S

#535 Fix retrieve request construct error
  milvus/client/grpc_handler.py
  milvus/client/prepare.py
  milvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/XS

#537 Remove tests
  .github/workflows/pull_request.yml
  Makefile
  milvus/client/http_handler.py
  milvus/client/pool.py
  requirements.txt
  tests/__init__.py
  tests/conftest.py
  tests/constants.py
  tests/factorys.py
  tests/test_bulk_insert.py
  tests/test_create_collection.py
  tests/test_drop_collection.py
  tests/test_get.py
  tests/test_get_collection_info.py
  tests/test_has_collection.py
  tests/test_insert.py
  tests/test_list_collections.py
  tests/test_load_collection.py
  tests/test_load_partitions.py
  tests/test_partition.py
  tests/test_search.py
  tests/utils.py
Labels: approved, ci-passed, lgtm, size/XXL

#538 Support column-based insert request
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/milvus.proto
  milvus/client/prepare.py
  milvus/grpc_gen/milvus_pb2.py
Labels: approved, ci-passed, lgtm, size/L

#540 Convert dim type to int
  milvus/client/abstract.py
Labels: approved, ci-passed, lgtm, size/XS

#541 Covert dim type to int
  milvus/client/abstract.py
Labels: approved, ci-passed, lgtm, size/XS

#542 Rename package
  examples/example.py
  examples/example_index.py
  pymilvus/__init__.py
  pymilvus/client/__init__.py
  pymilvus/client/abs_client.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/blob.py
  pymilvus/client/check.py
  pymilvus/client/client_hooks.py
  pymilvus/client/exceptions.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/hooks/__init__.py
  pymilvus/client/hooks/abstract.py
  pymilvus/client/pool.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/grpc_gen/__init__.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/schema_pb2.py
  pymilvus/settings.py
  pymilvus/utils.py
  tests/test_get.py
Labels: approved, ci-passed, lgtm, size/XS

#543 Fix bug for convert dim type
  pymilvus/client/abstract.py
Labels: approved, ci-passed, lgtm, size/XS

#544 Fix type error of dim
  pymilvus/client/prepare.py
Labels: approved, ci-passed, lgtm, size/XS

#545 Pymilvus connection timeout
  milvus/client/pool.py
  milvus/client/stub.py
Labels: approved, lgtm, size/S

#546 Add query rpc in proto
  grpc-proto/gen/common_pb2.py
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/gen/schema_pb2.py
  grpc-proto/milvus.proto
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/schema_pb2.py
Labels: approved, ci-passed, lgtm, size/XXL

#548 Expr can be None of search
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/XS

#549 Add Query API
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/L

#551 Fix bug for insert
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, ci-passed, lgtm, size/S

#552 Ignore _id field when pymiluvs-orm call pymilvus
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, ci-passed, lgtm, size/S

#553 Create release_event.yml to dispatch release published event to Milvus doc repo
  .github/workflows/release_event.yml
Labels: approved, ci-passed, lgtm, size/S

#554 Update proto
  grpc-proto/common.proto
  grpc-proto/gen/common_pb2.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/schema_pb2.py
Labels: approved, ci-passed, lgtm, size/M

#555 Fix bug for proto repeated field
  pymilvus/client/prepare.py
Labels: approved, ci-passed, lgtm, size/XS

#556 Add example for Query API
  examples/query.py
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/M

#557 Fix query grpc_handler
  examples/query.py
  pymilvus/client/grpc_handler.py
Labels: approved, ci-passed, lgtm, size/M

#558 Add length method for field_data
  examples/query.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/utils.py
Labels: approved, ci-passed, lgtm, size/M

#559 Check params of search request
  pymilvus/client/prepare.py
Labels: approved, ci-passed, lgtm, size/XS

#560 Error message should be str not list
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/XS

#562 Remove Get API
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/M

#563 Update proto
  grpc-proto/common.proto
  grpc-proto/gen/common_pb2.py
  pymilvus/grpc_gen/common_pb2.py
Labels: approved, ci-passed, lgtm, size/L

#564 Retry when rpc failure occurs
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/M

#565 Add comments for retry_on_rpc_failures
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/XS

#567 Redefine the auto_id and primary_key
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/gen/schema_pb2.py
  grpc-proto/milvus.proto
  grpc-proto/schema.proto
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/schema_pb2.py
Labels: approved, ci-passed, lgtm, size/XXL

#566 Make wait for healthy timeout short
  pymilvus/client/stub.py
Labels: ci-passed, lgtm, size/XS

#568 Search support target_entry
  examples/example.py
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/schema_pb2.py
  grpc-proto/milvus.proto
  grpc-proto/schema.proto
  pymilvus/client/abstract.py
  pymilvus/client/prepare.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/schema_pb2.py
Labels: approved, ci-passed, lgtm, size/XL

#569 Check dimension when creating collection
  pymilvus/client/prepare.py
Labels: approved, ci-passed, lgtm, size/XS

#570 Fix query raise exception
  examples/example.py
  examples/example_index.py
  examples/query.py
  pymilvus/client/grpc_handler.py
Labels: approved, ci-passed, lgtm, size/M

#572 Update the logic of waiting for flushed
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/milvus.proto
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
Labels: approved, ci-passed, lgtm, size/L

#573 Fix flush result
  pymilvus/client/grpc_handler.py
Labels: approved, ci-passed, size/XS

#574 Fix flush
  pymilvus/client/grpc_handler.py
Labels: ci-passed, size/XS

#571 Complement entity class
  examples/query.py
  pymilvus/client/abstract.py
Labels: approved, ci-passed, lgtm, size/M

#576 Raise more clear exception when passed dimension is invalid
  pymilvus/client/prepare.py
Labels: approved, ci-passed, lgtm, size/XS

#577 Add empty_collection error_code
  grpc-proto/common.proto
  grpc-proto/gen/common_pb2.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/grpc_gen/common_pb2.py
Labels: approved, ci-passed, lgtm, size/M

#578 Update example.py
  examples/example.py
Labels: approved, ci-passed, lgtm, size/L

#579 Check if output_fields is list
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, ci-passed, lgtm, size/XS

#580 Rename SearchResultFuture and InsertFuture
  pymilvus/__init__.py
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/S

#581 Add topks in searchResult
  grpc-proto/gen/schema_pb2.py
  grpc-proto/schema.proto
  pymilvus/client/abstract.py
  pymilvus/grpc_gen/schema_pb2.py
Labels: approved, ci-passed, lgtm, size/M

#582 fix bug
  pymilvus/client/abstract.py
Labels: approved, ci-passed, lgtm, size/XS

#584 Update PyMilvus version on README.md
  README.md
Labels: approved, ci-passed, lgtm, size/XS

#585 Fix recommended version of PyMilvus
  README.md
Labels: approved, ci-passed, lgtm, size/XS

#583 Check limit
  pymilvus/client/check.py
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/XS

#587 Call callback function when future.done() is called
  pymilvus/client/asynch.py
Labels: approved, ci-passed, lgtm, size/S
