Repository milvus-io/pymilvus, pull requests merged in 2021-09, with the labels that each got.

#683 Add api reference for calc_distance
  docs/source/api/utility.rst
Labels: approved, lgtm, size/M, ci-passed

#686 #Updated README.md with new documentation URL
  README.md
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to RC

#691 Change value of standalone deployment key to keep same as server.
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed

#678 Raise error if connect after closing connection
  Makefile
  pymilvus/client/stub.py
  pymilvus/orm/tests/conftest.py
  pymilvus/orm/tests/test_collection.py
  pymilvus/orm/tests/test_connections.py
  pymilvus/orm/tests/test_index.py
  pymilvus/orm/tests/test_partition.py
  pymilvus/orm/tests/test_types.py
  pymilvus/orm/tests/test_utility.py
Labels: approved, lgtm, size/L, ci-passed

#680 Fix not runnable examples
  examples/old_style_example.py
  examples/old_style_example_distance.py
  examples/old_style_example_index.py
Labels: approved, lgtm, size/L, ci-passed

#681 Make wait for healthy timeout controllable
  pymilvus/client/stub.py
Labels: approved, lgtm, size/XS, ci-passed

#692 An example of getting an existing collection
  examples/collection.py
Labels: approved, lgtm, size/S, ci-passed

#695 Fix Milvus init error
  pymilvus/client/stub.py
Labels: approved, lgtm, size/XS, ci-passed

#699 Remove check connect
  pymilvus/client/stub.py
Labels: approved, lgtm, size/M, ci-passed

#703 Raise NotImplementError when calling delete()
  pymilvus/client/stub.py
Labels: approved, lgtm, size/XS, ci-passed

#705 Update version in document
  README.md
  docs/source/conf.py
  docs/source/install.rst
Labels: approved, lgtm, size/S, ci-passed

#706 Update SchemaNotReady exception msg when collection not exist
  pymilvus/orm/pymilvus_orm/collection.py
  pymilvus/orm/pymilvus_orm/exceptions.py
Labels: approved, lgtm, size/XS, ci-passed

#708 support _async paramter for Load() interfance
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/orm/pymilvus_orm/collection.py
Labels: approved, lgtm, size/S, ci-passed

#710 Check field name when create index
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/M, ci-passed

#711 Fix nightly-ci schedule
  .github/workflows/nightly_ci.yml
Labels: approved, lgtm, size/XS, ci-passed

#713 Fix #7613
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/S, ci-passed

#712 Add CONTRIBUTING_CN.md
  CONTRIBUTING_CN.md
Labels: approved, lgtm, size/L, ci-passed

#716 Fix nightly ci github action
  .github/workflows/nightly_ci.yml
Labels: approved, lgtm, size/XS, ci-passed

#720 Implement alias api
  examples/collection.py
  grpc-proto/common.proto
  grpc-proto/gen/common_pb2.py
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/milvus.proto
  pymilvus/client/abstract.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/orm/pymilvus_orm/collection.py
Labels: approved, lgtm, size/XXL, ci-passed

#719 Remove extra pymilvus_orm directory
  .gitignore
  Makefile
  pymilvus/__init__.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/constants.py
  pymilvus/orm/default_config.py
  pymilvus/orm/exceptions.py
  pymilvus/orm/future.py
  pymilvus/orm/index.py
  pymilvus/orm/mutation.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pymilvus/orm/pymilvus_orm/__init__.py
  pymilvus/orm/schema.py
  pymilvus/orm/search.py
  pymilvus/orm/tests/conftest.py
  pymilvus/orm/types.py
  pymilvus/orm/utility.py
  tests/conftest.py
  tests/mock_milvus.py
  tests/mock_result.py
  tests/pytest.ini
  tests/test_collection.py
  tests/test_connections.py
  tests/test_index.py
  tests/test_partition.py
  tests/test_schema.py
  tests/test_types.py
  tests/test_utility.py
  tests/utils.py
Labels: enhancement, approved, lgtm, size/M, ci-passed

#721 Add example for alias
  examples/collection.py
Labels: approved, lgtm, size/M, ci-passed

#729 [skip ci] Add Milvus x Hacktoberfest banner
  README.md
Labels: approved, lgtm, size/XS, ci-passed

#730 Change startup logic: wait enough time for server healthy
  pymilvus/client/stub.py
Labels: approved, lgtm, size/S, ci-passed

#726 Remove utils.py
  pymilvus/utils.py
Labels: approved, lgtm, size/S, ci-passed

#735 Description for delete api
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/S, ci-passed

#724 Remove hooks and client_hooks
  pymilvus/client/client_hooks.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/hooks/__init__.py
  pymilvus/client/hooks/abstract.py
  pymilvus/client/stub.py
Labels: approved, lgtm, size/L, ci-passed

#715 Adds __str__ for baseloop (Search results)
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed

#733 For search function adding precision control
  examples/example.py
  examples/hello_milvus.py
  examples/partition.py
  pymilvus/client/abstract.py
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/M, ci-passed

#737 Add __str__ methods to orm SearchResult and Hits objects
  pymilvus/orm/search.py
Labels: approved, lgtm, size/XS, ci-passed

#738 For old style search function also adding a round decimal paramter
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
Labels: approved, lgtm, size/M, ci-passed

#736 Update ORM SearchResult and Hits objects to use consistent types for index gets and slice gets
  pymilvus/orm/search.py
Labels: approved, lgtm, size/XS, ci-passed
