Repository milvus-io/pymilvus, pull requests merged in 2021-03, with the labels that each got.

#430 Update README version table
  README.md
Labels: documentation

#448 Update query-results documentation
  CHANGELOG.md
  docs/source/results.rst
  docs/source/results.rst.bak
Labels: PR | automerge, PR | ignore CI, documentation

#455 Fix documentation bug
  docs/source/install.rst
  docs/source/query.rst
  docs/source/query.rst.bak
  docs/source/res/Intro_to_Indexes.md
  docs/source/res/query.md
  docs/source/tutorial.rst
  milvus/client/stub.py
Labels: PR | automerge, PR | ignore CI, documentation

#459 1.0 update
  .github/scripts/server/milvus.yaml
  .github/scripts/server/server.yml
  .github/workflows/ci.yml
  .github/workflows/lint.yml
  .gitignore
  .mergify/config.yml
  README.md
  examples/example.py
  milvus/__init__.py
  milvus/client/abstract.py
  milvus/client/asynch.py
  milvus/client/check.py
  milvus/client/client_hooks.py
  milvus/client/exceptions.py
  milvus/client/grpc_handler.py
  milvus/client/hooks/__init__.py
  milvus/client/http_handler.py
  milvus/client/pool.py
  milvus/client/prepare.py
  milvus/client/stub.py
  milvus/client/types.py
  pylint.conf
  setup.py
  tests/test_collection.py
Labels: PR | cherry-pick to 1.x, PR | cherry-picked to master

#461 [ci] All test pass
  .mergify/config.yml
  CHANGELOG.md
  conftest.py
  factorys.py
  milvus/client/check.py
  milvus/client/stub.py
  tests/test_insert.py
  tests/test_pool.py
Labels: PR | automerge, PR | cherry-pick to 1.x, PR | cherry-pick to master, PR | trigger CI

#465 Fix `inset` > `insert` typo.
  docs/source/tutorial.rst
Labels: documentation

#467 Clear surplus code and improve documentation
  .gitignore
  .mergify/config.yml
  docs/README.md
  docs/source/contribute.rst
  milvus/client/abstract.py
  milvus/client/grpc_handler.py
Labels: PR | cherry-pick to 1.x, PR | cherry-pick to master, PR | ignore CI

#468 Add IndexType and MetricType in documentation & Support cross-referencing
  README.md
  docs/source/api.rst
  milvus/client/stub.py
  milvus/client/types.py
Labels: PR | automerge, PR | cherry-pick to 1.x, PR | cherry-pick to master, PR | ignore CI, documentation

#471 Update readme Compatibility version
  README.md
Labels: PR | automerge, PR | cherry-pick to 1.x, PR | cherry-pick to master, PR | ignore CI, documentation

#473 Update readme Compatibility version (#471)
  README.md
Labels: PR | cherry-pick, documentation

#472 Update readme Compatibility version (#471)
  README.md
Labels: PR | cherry-pick, documentation
