Repository milvus-io/pymilvus, pull requests merged in 2021-12, with the labels that each got.

#838 Add fieldID in DescribeSegmentResponse
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/proto/milvus.proto
Labels: approved, lgtm, size/L, ci-passed

#841 Move aliases operations into utility
  docs/source/api/utility.rst
  examples/collection.py
  pymilvus/orm/collection.py
  pymilvus/orm/utility.py
  requirements.txt
Labels: approved, lgtm, size/L, ci-passed

#839 Enable get git commit for a given version
  .github/workflows/pull_request.yml
  pymilvus/client/__init__.py
  tests/test_check.py
Labels: approved, lgtm, size/M, ci-passed

#845 Support to configure the consistency level
  pymilvus/client/abstract.py
  pymilvus/client/constants.py
  pymilvus/client/exceptions.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/client/ts_utils.py
  pymilvus/client/types.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/proto/common.proto
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  tests/test_ts_utils.py
  tests/test_types.py
Labels: approved, lgtm, ci-passed, size/XL

#847 Support guarantee_timestamp & travel_timestamp for query
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/client/ts_utils.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/L, ci-passed

#848 Add hellomilvus in jupyter notebook
  examples/hello_milvus.ipynb
Labels: approved, lgtm, size/L, ci-passed

#849 Add a English version of contributing_cn.md
  CONTRIBUTING.md
Labels: approved, lgtm, size/M, ci-passed

#852 Update version in documentation
  README.md
  docs/source/conf.py
  docs/source/install.rst
Labels: documentation, lgtm, size/S, ci-passed
