Repository milvus-io/pymilvus, pull requests merged in 2021-08, with the labels that each got.

#626 Fixbug: use derived BaseException
  pymilvus/client/grpc_handler.py
Labels: approved, ci-passed, lgtm, size/XS

#627 Change the logic about waiting for loading collection/partitions
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/milvus.proto
  pymilvus/client/configs.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/grpc_gen/milvus_pb2.py
Labels: approved, ci-passed, lgtm, size/XL

#629 Add rc3 for README
  README.md
Labels: approved, lgtm, size/XS, ci-passed

#632 Remove publish release package github action
  .github/workflows/publish_release_package.yml
  Makefile
Labels: approved, lgtm, size/M, ci-passed

#633 Comment not working target codecov
  Makefile
Labels: approved, lgtm, size/XS, ci-passed

#635 Fix cannot import DefaultConfig problem
  pymilvus/__init__.py
Labels: approved, lgtm, size/XS, ci-passed

#637 Fix cannot import ExceptionsMessage error
  pymilvus/__init__.py
Labels: approved, lgtm, size/XS, ci-passed

#638 Update workflows for web-content
  .github/workflows/doc_update_event.yml
  .github/workflows/release_event.yml
Labels: approved, lgtm, size/M, ci-passed

#644 Sync milvus.proto from milvus master branch
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/milvus.proto
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
Labels: approved, lgtm, size/XXL, ci-passed

#645 Limit the grpc version in setup.py
  setup.py
Labels: approved, lgtm, size/XS, ci-passed

#647 Improper error returned by calc_distance
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed

#648 Improper error returned by calc_distance
  examples/old_style_example_distance.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/pymilvus_orm/utility.py
Labels: approved, lgtm, size/M, ci-passed

#650 calc_distance missed partition name
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed

#655 calc_distance error message bug
  examples/example.py
  examples/old_style_example_distance.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/pymilvus_orm/utility.py
Labels: approved, lgtm, size/M, ci-passed

#656 check calc_distance params
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/S, ci-passed

#658 Add util function to drop_collection
  docs/source/api/utility.rst
  pymilvus/__init__.py
  pymilvus/client/stub.py
  pymilvus/orm/pymilvus_orm/utility.py
  pymilvus/orm/tests/conftest.py
  pymilvus/orm/tests/mock_milvus.py
  pymilvus/orm/tests/test_collection.py
  pymilvus/orm/tests/test_connections.py
  pymilvus/orm/tests/test_index.py
  pymilvus/orm/tests/test_partition.py
  pymilvus/orm/tests/test_schema.py
  pymilvus/orm/tests/test_types.py
  pymilvus/orm/tests/test_utility.py
  pymilvus/orm/tests/utils.py
Labels: approved, lgtm, size/L, ci-passed

#659 Add Nightly CI
  .github/workflows/nightly_ci.yml
  ci/docker/milvus/docker-compose.yml
  ci/scripts/docker_image_find_tag.sh
Labels: approved, lgtm, size/L, ci-passed

#673 Remove retry logic when drop collection with deadline error
  pymilvus/client/stub.py
Labels: approved, lgtm, size/XS, ci-passed

#674 Change newest version to rc5
  README.md
  docs/source/conf.py
  docs/source/contribute.rst
  docs/source/install.rst
  docs/source/tutorial.rst
Labels: approved, lgtm, size/S, ci-passed

#676 Add delete api
  docs/source/api/collection.rst
  docs/source/api/partition.rst
  docs/source/api/utility.rst
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/milvus.proto
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/orm/pymilvus_orm/collection.py
  pymilvus/orm/pymilvus_orm/partition.py
Labels: approved, lgtm, ci-passed, size/XL

#675 Change newest version to rc5
  README.md
  docs/source/conf.py
  docs/source/contribute.rst
  docs/source/install.rst
  docs/source/tutorial.rst
Labels: approved, lgtm, size/S
