Repository milvus-io/pymilvus, pull requests merged in 2021-07, with the labels that each got.

#592 Check dimension of query vectors
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, ci-passed, lgtm, size/M

#593 Add slack channel link into readme
  README.md
Labels: approved, ci-passed, lgtm, size/XS

#594 Optimize the workflow of future object
  pymilvus/client/asynch.py
Labels: approved, ci-passed, lgtm, size/M

#596 Fix 6034
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/XS

#600 Init unittest
  Makefile
  pymilvus/client/grpc_handler.py
  pymilvus/client/pool.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pytest.ini
  requirements.txt
  tests/test_create_collection.py
  tests/test_get.py
Labels: approved, ci-passed, lgtm, size/L

#602 Fix chaos testing failed
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/XS

#603 Fix float vector result handle
  pymilvus/client/abstract.py
Labels: approved, ci-passed, lgtm, size/XS

#604 implement calc_distance() api
  examples/example_distance.py
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/milvus.proto
  pymilvus/client/abs_client.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
Labels: approved, ci-passed, lgtm, size/XXL

#605 Support binary_vector in target_entry
  pymilvus/client/abstract.py
Labels: approved, ci-passed, lgtm, size/S

#606 Fix async bug
  pymilvus/client/asynch.py
Labels: approved, ci-passed, lgtm, size/M

#607 Add rc2 for README
  README.md
Labels: approved, ci-passed, lgtm, size/XS

#608 Fix search future
  pymilvus/client/asynch.py
Labels: approved, ci-passed, lgtm, size/XS

#609 Check if anns_field is legal
  pymilvus/client/check.py
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/XS

#610 Check if search data is legal
  pymilvus/client/check.py
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/S

#611 add FieldId into FieldData
  grpc-proto/gen/schema_pb2.py
  grpc-proto/schema.proto
  pymilvus/grpc_gen/schema_pb2.py
Labels: approved, ci-passed, lgtm, size/M

#613 Check partition_names and output_fields when search
  pymilvus/client/check.py
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/S

#616 Set default calc_distance metric to "L2"
  pymilvus/client/grpc_handler.py
  pymilvus/settings.py
Labels: approved, ci-passed, lgtm, size/XS

#620 Fix load_collection timeout not working problem
  pymilvus/client/grpc_handler.py
Labels: approved, ci-passed, lgtm, size/M

#621 Remove unused abs_client avoid confusing
  pymilvus/client/abs_client.py
  pymilvus/client/grpc_handler.py
Labels: approved, ci-passed, lgtm, size/XL

#622 Fix bug for retry when rpc failure
  pymilvus/client/stub.py
Labels: approved, ci-passed, lgtm, size/M

#623 Support binary vector
  pymilvus/client/grpc_handler.py
  pymilvus/client/utils.py
Labels: approved, ci-passed, lgtm, size/XS

#618 Enhance log when create index failed
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/milvus.proto
  pymilvus/client/grpc_handler.py
  pymilvus/grpc_gen/milvus_pb2.py
Labels: approved, ci-passed, lgtm, size/L

#624 Increase throughput of search
  pymilvus/client/configs.py
  pymilvus/client/prepare.py
Labels: approved, ci-passed, lgtm, size/XS

#625 Increase throughput of search
  pymilvus/client/configs.py
Labels: approved, ci-passed, lgtm, size/XS
