Repository milvus-io/pymilvus, pull requests merged in 2021-11, with the labels that each got.

#792 Fixed all buggy format of `raises` doc comment
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/L, ci-passed, Hacktoberfest

#793 Check the travel timestamp
  pymilvus/client/check.py
  pymilvus/client/stub.py
Labels: approved, lgtm, size/XS, ci-passed

#794 Change docs for 2.0.0rc8
  README.md
  docs/source/conf.py
  docs/source/install.rst
Labels: approved, lgtm, size/S, ci-passed

#795 Change package name for perf branch
  .github/workflows/publish_dev_package.yml
  setup.py
Labels: approved, lgtm, size/XS, ci-passed

#796 Trigger push perf package
  .github/workflows/publish_dev_package.yml
  README.md
Labels: approved, lgtm, size/S, ci-passed

#797 Do not divide search requests
  pymilvus/client/configs.py
Labels: approved, lgtm, size/XS, ci-passed

#801 Update the docstring of insert and delete method
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/S, ci-passed

#757 Add load balance
  docs/source/api/utility.rst
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/milvus.proto
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/L, ci-passed

#803 Enable delete function
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed

#806 Enhance pymilvus proto gen procedure
  Makefile
  grpc-proto/gen/common_pb2.py
  grpc-proto/gen/milvus_pb2.py
  grpc-proto/gen/milvus_pb2_grpc.py
  grpc-proto/gen/schema_pb2.py
  grpc-proto/python_gen.sh
  pymilvus/grpc_gen/__init__.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/proto/common.proto
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/grpc_gen/proto/python_gen.sh
  pymilvus/grpc_gen/proto/schema.proto
Labels: approved, lgtm, size/XXL, ci-passed

#807 Add compact method in collection
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/client/types.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/proto/common.proto
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/L, ci-passed

#808 Fix broken link in doc
  docs/source/contribute.rst
  docs/source/res/Intro_to_Indexes.md
  docs/source/tutorial.rst
Labels: approved, lgtm, size/S, ci-passed

#812 fix broken link in doc
  docs/source/contribute.rst
  docs/source/res/Intro_to_Indexes.md
  docs/source/tutorial.rst
Labels: approved, size/S

#811 Make scheme print nicer
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed

#816 Seek to latest
  Makefile
  grpc-proto/gen/common_pb2.py
  grpc-proto/gen/schema_pb2.py
  grpc-proto/python_gen.sh
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/grpc_gen/__init__.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/proto/common.proto
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/grpc_gen/proto/python_gen.sh
  pymilvus/grpc_gen/proto/schema.proto
Labels: approved, size/XXL

#805 Set params in load_balance as optional
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/XS, ci-passed

#817 Fix typos in types
  pymilvus/client/types.py
Labels: approved, lgtm, size/S, ci-passed

#789 Rewrite the example.py
  examples/example.py
Labels: approved, lgtm, size/L, ci-passed

#820 Add method of waiting compaction completed
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed

#821 Set default consistency level to session
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/M, ci-passed

#822 add graceful time
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/L

#823 Revert "Set default consistency level to session"
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/M, ci-passed

#826 Check param for guarantee_timestamp
  pymilvus/client/check.py
  pymilvus/client/stub.py
Labels: approved, lgtm, size/XS, ci-passed

#818 Add hellomilvus 2.0
  examples/hello_milvus.py
  pymilvus/orm/collection.py
  pymilvus/orm/mutation.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed

#828 Add GetFlushState method
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/proto/milvus.proto
Labels: approved, lgtm, size/L, ci-passed

#827 Set default consistency level to session
  pymilvus/client/abstract.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/singleton_utils.py
  pymilvus/client/ts_utils.py
  tests/test_ts_utils.py
Labels: approved, lgtm, size/L, ci-passed

#832 Update the reviewers and approvers
  OWNERS
Labels: approved, lgtm, size/S, ci-passed

#831 Add util functions to make hybrid timestamp
  docs/source/api/utility.rst
  pymilvus/__init__.py
  pymilvus/client/constants.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/ts_utils.py
  pymilvus/client/utils.py
  pymilvus/orm/utility.py
  tests/test_check.py
  tests/test_ts_utils.py
Labels: approved, lgtm, size/L, ci-passed

#829 Fix hello milvus exception
  examples/hello_milvus.py
Labels: approved, lgtm, size/XS, ci-passed

#833 [skip ci] Revise TS API Reference
  docs/source/api/utility.rst
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/S, ci-passed

#835 Remove hacktoberfest banner
  README.md
Labels: approved, lgtm, size/XS, ci-passed
