Repository milvus-io/pymilvus, pull requests merged in 2022-05, with the labels that each got.

#974 Fix connection unable to connect to old alias
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/M, ci-passed

#978 Revert "Fix connection unable to connect to old alias (#974)"
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/M, ci-passed

#967 Support tls for self-signed certificate
  examples/cert/ca.pem
  examples/cert/client.key
  examples/cert/client.pem
  examples/example_tls.py
  pymilvus/client/grpc_handler.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/L, ci-passed

#979 Add default max_length params when construct from df
  examples/example_str.py
  pymilvus/client/configs.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed

#976 Add API for ListImportTasks
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/client/types.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed

#982 Create Index with index_name
  pymilvus/orm/index.py
Labels: approved, lgtm, size/XS, ci-passed

#983 Fix no default max_len params when auto_id=true
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed

#986 Add unittests framework for grpc_handler
  pymilvus/client/grpc_handler.py
  tests/conftest.py
  tests/test_grpc_handler.py
Labels: approved, lgtm, size/M, ci-passed

#987 Fix collection.Indexes with index_name
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
  pymilvus/orm/index.py
  tests/test_collection.py
Labels: approved, lgtm, size/M, ci-passed

#980 fix grpc support tls for self-signed certificate
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/S, ci-passed

#989 Fix some docs
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed

#990 Fix some docs
  pymilvus/orm/index.py
Labels: approved, lgtm, size/XS, ci-passed

#991 Add ut for add_connection
  Makefile
  pymilvus/orm/connections.py
  tests/test_collection.py
  tests/test_connections.py
Labels: approved, lgtm, size/L, ci-passed

#994 Fix dup index_name params in describe_index when create_index
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed

#995 Add czs007 as reviewer and approver
  OWNERS
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.0

#996 Add czs007 as reviewer and approver (#995)
  OWNERS
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#997 Fix connect and add ut for connect
  pymilvus/orm/connections.py
  tests/test_connections.py
Labels: kind/bug, approved, lgtm, size/L, ci-passed

#1001 Remove logic of splitting nq and delete unused code
  pymilvus/client/configs.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/L, ci-passed

#1007 Enhance mergify on branch 2.0
  .github/mergify.yml
Labels: approved, lgtm, ci-passed

#1006 Fix seach hangs forever while server unavaliable
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
  tests/e2e_issues/test_issue_16835.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1011 Maintain session consistency according to collection name
  pymilvus/client/grpc_handler.py
  pymilvus/client/ts_utils.py
  tests/test_ts_utils.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1012 Enable timeout to control retry times
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/decorators.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed, PR | cherry-pick to 2.0, dco-passed

#1016 Fix nightly index out of range
  pymilvus/client/stub.py
  pymilvus/decorators.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1008 Fix mergify unable to label ci-pass on branch 2.0
  .github/mergify.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1017 Add Milvus Unavaliable Exception
  pymilvus/__init__.py
  pymilvus/decorators.py
  pymilvus/exceptions.py
  tests/conftest.py
  tests/test_grpc_handler.py
Labels: kind/bug, approved, lgtm, size/M, ci-passed, dco-passed

#1014 Set guarantee_timestamp to 2 in case of Bounded consistency level
  pymilvus/client/constants.py
  pymilvus/client/ts_utils.py
  tests/test_ts_utils.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1018 Cherry pick of (#1012) and (#1016)
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/decorators.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  pymilvus/orm/utility.py
Labels: PR | cherry-pick, approved, lgtm, size/L, ci-passed, dco-passed

#1019 Add Milvus Unavaliable Exception (#1017)
  pymilvus/__init__.py
  pymilvus/client/exceptions.py
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
  pymilvus/orm/exceptions.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed
