Repository milvus-io/pymilvus, pull requests merged in 2022-09, with the labels that each got.

#1124 Fix readme link
  README.md
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1126 Enable offset in search_params
  pymilvus/client/prepare.py
  tests/test_prepare.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1125 Fix readme link
  README.md
Labels: approved, lgtm, size/XS, ci-passed

#1130 Enable proto check at branch 2.1
  .github/workflows/check_milvus_proto.yml
  setup.py
Labels: approved, lgtm, size/XS, ci-passed

#1134 Fix binary vector insert performance issue
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/XS, ci-passed

#1135 Fix binary vector insert performance issue
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1136 Disable bulkload interface
  examples/example_bulkload.py
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, ci-passed, size/XL

#1138 Refine CreateCollectionRequest
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/schema.py
  tests/test_prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1139 Fix error message with type error
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  tests/test_check.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1140 Add type check for secure in connect
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1101 Enable DataType.BOOL (#1098)
  pymilvus/client/abstract.py
  pymilvus/client/grpc_handler.py
Labels: PR | cherry-pick, approved, lgtm, size/S, ci-passed

#1146 Catch rate limit and force deny error
  pymilvus/decorators.py
  tests/test_decorators.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1148 Remove not in use LOGGER
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/orm/types.py
  pymilvus/settings.py
  tests/test_index.py
  tests/test_partition.py
  tests/test_schema.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1153 fix invalid index type is not str
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed

#1166 Add autoindex type
  pymilvus/client/utils.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1164 Fix partial orm api missing kwargs
  pymilvus/orm/collection.py
  pymilvus/orm/index.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1173 Revert "Refine Exception handling"
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/check.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/singleton_utils.py
  pymilvus/client/stub.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/decorators.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/constants.py
  pymilvus/orm/index.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
  pymilvus/orm/utility.py
  pymilvus/settings.py
  tests/test_connections.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed
