Repository milvus-io/pymilvus, pull requests merged in 2022-08, with the labels that each got.

#1088 Remove usage of HasCollection
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  tests/test_grpc_handler.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1089 Remove flush in num_entities
  examples/hello_milvus.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1093 Rename Credential api names
  examples/user.py
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1098 Enable DataType.BOOL
  pymilvus/client/abstract.py
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-pick to 2.1

#1103 Fix the `list_roles` function in the `utility.py` file
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1105 Update `rbac` function usage example file
  examples/role_and_privilege.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1106 Handle the `sed` and `grep` difference between Linux and Darwin
  check_proto_product.sh
  pymilvus/grpc_gen/python_gen.sh
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1102 Change doc versions to 2.1.1
  README.md
  docs/source/conf.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1091 [issue:1090] read default connection config from env MILVUS_DEFAULT_C…
  pymilvus/__init__.py
  pymilvus/exceptions.py
  pymilvus/orm/connections.py
  pymilvus/orm/default_config.py
  tests/test_connections.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1111 Delete useless index params
  pymilvus/client/utils.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1110 Fix mergify regex
  .github/mergify.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1109 Merge example multiple index with example index
  examples/example_index.py
  examples/example_multiple_index.py
Labels: approved, lgtm, size/L, ci-passed

#1113 Fix the `is_exist` function in the `Role` object
  pymilvus/orm/role.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1114 Improve the result of `get_users` function in the `Role` object
  pymilvus/orm/role.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1119 Add upbound for grpcio in-compatibility 1.49.0.rc1
  setup.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1112 Support retry when requests are rejected due to rate limit
  pymilvus/decorators.py
  tests/test_decorators.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1116 add client log level and client quest id for rpc calls
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1118 Raise exception if wait collection loaded timeout
  pymilvus/client/grpc_handler.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, dco-passed
