Repository milvus-io/pymilvus, pull requests merged in 2022-01, with the labels that each got.

#853 Remove retry after search deadline
  pymilvus/client/stub.py
Labels: approved, lgtm, size/XS, ci-passed

#857 Fix hello milvus error
  examples/hello_milvus.ipynb
  examples/hello_milvus.py
Labels: approved, lgtm, size/S, ci-passed

#858 Downgrade ConsistencyLevel to Eventually when fetched zero guarantee_ts
  pymilvus/client/ts_utils.py
Labels: enhancement, approved, lgtm, size/XS, ci-passed

#846 Mark 1.x APIs as deprecated
  docs/source/api/connections.rst
  pymilvus/client/abstract.py
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/pool.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/decorators.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/default_config.py
  pymilvus/orm/index.py
  pymilvus/orm/partition.py
  pymilvus/orm/utility.py
  tests/test_collection.py
  tests/test_connections.py
  tests/test_create_collection.py
  tests/test_index.py
  tests/test_utility.py
Labels: approved, lgtm, size/XXL, ci-passed

#862 Fixbug: consistency_level not set
  pymilvus/client/grpc_handler.py
  pymilvus/orm/types.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed

#866 Fix raising BaseException bug
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed

#867 Fix utility wait_for_loading method
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/XS, ci-passed

#859 Add Dockerfile
  Dockerfile
Labels: approved, lgtm, size/XS, ci-passed

#863 Limit the package dependency
  requirements.txt
  setup.py
Labels: approved, lgtm, size/S, ci-passed

#869 [skip e2e] Revise API reference
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/M, ci-passed

#870 Update tutorial.rst
  docs/source/tutorial.rst
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/L, ci-passed

#871 Fix BaseExceptions in decorators
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed

#873 Add more detailed log before raising grpc.RpcError
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed
