Repository milvus-io/pymilvus, pull requests merged in 2022-11, with the labels that each got.

#1214 Don't set default_idx as index name when drop index
  pymilvus/client/stub.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1215 Only allow one file for row-based import
  examples/example_bulkload.py
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1217 Make error message more clear when schema mismatch
  pymilvus/orm/collection.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1218 Modify bulkinsert example
  examples/example_bulkload.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1222 Fix error message for primary key type
  pymilvus/exceptions.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1223 Optimize some low efficient code
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  tests/test_prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1220 Change doc string of Collection init and property
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1226 Fix mutation results print error
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1225 Update docs for collection
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1228 Modify bulkinsert example
  examples/example_bulkinsert.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1231 Enable github actions on branch 2.2
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
Labels: approved, lgtm, size/XS, ci-passed

#1232 Update Readme to the latest pymilvus version
  README.md
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1234 Update mergify rules for branch 2.x
  .github/mergify.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1233 Update Readme to the latest pymilvus version
  README.md
Labels: approved, lgtm, size/S, ci-passed

#1235 Add the example comments for rbac methods
  pymilvus/orm/role.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/L, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1237 Enhance expression of search
  examples/example.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1242 Update docs for Collection
  pymilvus/orm/collection.py
Labels: approved, lgtm, ci-passed, size/XL, PR | cherry-pick to 2.2, dco-passed
