Repository milvus-io/pymilvus, pull requests merged in 2022-04, with the labels that each got.

#938 Update doc version
  docs/source/conf.py
Labels: documentation, approved, lgtm, ci-passed, PR | cherry-pick to 2.0

#935 Fix create_partition doc string (#899)
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#933 Update approvers and reviewers in OWNERS file (#901)
  OWNERS
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#931 Fix pymilvus unable to download on python3.8 (#919)
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
  requirements.txt
  setup.py
Labels: PR | cherry-pick, approved, lgtm, size/S, ci-passed

#932 Fix mergify rules for python3.8 (#921)
  .github/mergify.yml
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#934 Fix readme bug (#900)
  README.md
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#936 Fix loading progress output (#902)
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
  pymilvus/orm/utility.py
Labels: PR | cherry-pick, approved, lgtm, size/M, ci-passed

#937 Add support for numpy.ndarray for vector field (#904)
  examples/hello_milvus.ipynb
  examples/hello_milvus.py
  pymilvus/orm/prepare.py
Labels: PR | cherry-pick, approved, lgtm, size/L, ci-passed

#939 Update doc version (#938)
  docs/source/conf.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#940 Change scm version scheme to support 2.1.0.devx
  setup.py
Labels: approved, lgtm, size/XS, ci-passed

#941 Make 2.0 branch function properly
  .github/mergify.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
  setup.py
Labels: approved, lgtm, size/S, ci-passed

#942 Update pymilvus for memory replica
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/proto/common.proto
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/grpc_gen/proto/schema.proto
  pymilvus/grpc_gen/schema_pb2.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, ci-passed, size/XL

#945 Implement get_replicas in SDK
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/client/types.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  tests/test_types.py
Labels: approved, lgtm, ci-passed, size/XL

#948 Implement BulkLoad APIs
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/client/types.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, kind/feature, size/L, ci-passed

#947 Mep 27: Support Basic Authentication
  examples/credential.py
  pymilvus/__init__.py
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/interceptor.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/orm/utility.py
Labels: approved, lgtm, kind/feature, ci-passed, size/XL

#949 Fix loading progress check
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed

#950 Add multithreading example
  examples/multithreading_hello_milvus.py
Labels: approved, lgtm, size/M, ci-passed

#952 Update bulk_load proto
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/proto/common.proto
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/L, ci-passed

#953 Add docstring for connect
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed

#954 Fix get_bulk_load_state
  pymilvus/client/prepare.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed

#955 Unify Execption module and accelerate data type checking
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/check.py
  pymilvus/client/entity_helper.py
  pymilvus/client/exceptions.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/decorators.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/index.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
  pymilvus/orm/utility.py
  tests/test_types.py
Labels: approved, lgtm, size/L, ci-passed

#957 Update credential api
  examples/credential.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/L, ci-passed

#958 Support string type in search/query result
  pymilvus/client/abstract.py
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/M, ci-passed

#956 Update load_partitions and load_balance proto
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/proto/common.proto
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, ci-passed, size/XL

#959 Fix parse empty ids
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed

#961 Support create index for scalar field
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed

#962 Fix insert string data from DataFrame
  examples/example_str.py
  examples/old_style_example_str.py
  pymilvus/client/configs.py
  pymilvus/client/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed

#960 Alter group_nodes setter
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  tests/test_types.py
Labels: approved, lgtm, size/S, ci-passed

#964 Refactor connections
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed

#966 Add more returns in loading_progress
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed

#968 Fix replica_number param in stub
  pymilvus/client/stub.py
Labels: approved, lgtm, size/XS, ci-passed

#969 Fix err msg when max_length_per_row is too large
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed

#971 Fix collection construct from dataframe
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed

#972 Fix schema mismatch when max_length_per_row is specified
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed
