Repository milvus-io/pymilvus, pull requests merged in 2022-07, with the labels that each got.

#1058 Fix connect with Milvus
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1060 Add err_count & succ_count to mutation result
  pymilvus/client/abstract.py
  pymilvus/orm/mutation.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1061 Fix show partitions unable to show all
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, dco-passed

#1062 Fix mutation result
  pymilvus/client/abstract.py
  pymilvus/orm/mutation.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1063 Upgrade grpc version to 1.47.0
  requirements.txt
  setup.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1067 Fix CVE-2022-31116 by allow upgrade ujson include 5.4.0
  requirements.txt
  setup.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1071 Fix metric type in hello milvus
  examples/hello_milvus.ipynb
  examples/hello_milvus.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1072 Descreasing initial back off time
  pymilvus/decorators.py
  tests/test_decorators.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1054 Add VarChar in hello milvus
  examples/hello_milvus.ipynb
  examples/hello_milvus.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1073 Prepare to release pymilvus2.1.0
  README.md
  docs/source/conf.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1075 Fix typo `Unavaliable`
  pymilvus/__init__.py
  pymilvus/decorators.py
  pymilvus/exceptions.py
  tests/test_decorators.py
  tests/test_grpc_handler.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1078 Upgrade protoc generated files
  .github/workflows/check_milvus_proto.yml
  pymilvus/__init__.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/schema_pb2.py
  requirements.txt
  setup.py
  tests/test_check.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed, PR | cherry-pick to 2.1

#1079 Enable branch 2.1 to publish dev packge
  .github/workflows/publish_dev_package.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1080 Cherry pick #1075 and #1078
  .github/workflows/check_milvus_proto.yml
  pymilvus/__init__.py
  pymilvus/decorators.py
  pymilvus/exceptions.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/schema_pb2.py
  requirements.txt
  setup.py
  tests/test_check.py
  tests/test_decorators.py
  tests/test_grpc_handler.py
Labels: PR | cherry-pick, approved, lgtm, size/XXL, ci-passed

#1082 Fix mergify rules
  .github/mergify.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1081 Fix ut action for branch 2.1
  .github/workflows/pull_request.yml
Labels: approved, lgtm, size/XS, ci-passed
