Repository milvus-io/pymilvus, pull requests merged in 2022-10, with the labels that each got.

#1176 fix broken _async in delete()
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1178 Remove print when rate limit
  pymilvus/decorators.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1155 Support create flat index
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1185 Remove calculate distance API
  docs/source/api/utility.rst
  examples/old_style_example_distance.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1186 Rename bulkload to bulkinsert
  examples/example_bulkload.py
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/client/types.py
  pymilvus/orm/collection.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1187 Fix a typo
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1188 Add example for pagination
  examples/hello_milvus.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1189 Fix a typo
  pymilvus/client/stub.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1180 Refine Exception handling (#1173)
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/check.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/singleton_utils.py
  pymilvus/client/stub.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/decorators.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/constants.py
  pymilvus/orm/index.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
  pymilvus/settings.py
  tests/test_connections.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1192 Dropping index must happen without collection being loaded
  pymilvus/orm/collection.py
  tests/test_collection.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1194 Add more information when wait timeout
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1197 Add code checker for each pull request
  .github/mergify.yml
  .github/workflows/code_checker.yml
  pylint.conf
  pymilvus/__init__.py
  pymilvus/client/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/blob.py
  pymilvus/client/check.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/interceptor.py
  pymilvus/client/prepare.py
  pymilvus/client/singleton_utils.py
  pymilvus/client/stub.py
  pymilvus/client/ts_utils.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/decorators.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/default_config.py
  pymilvus/orm/mutation.py
  pymilvus/orm/partition.py
  pymilvus/orm/role.py
  pymilvus/orm/schema.py
  pymilvus/orm/search.py
  pymilvus/orm/utility.py
  pymilvus/settings.py
  requirements.txt
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1198 Only send drop collection request to milvus server
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1195 Remove flush in create index
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1200 Remove is_row_based flag of bulk_insert()
  examples/example_bulkload.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1199 Do not set default index name for creating index
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1201 Don't set default index name when drop index
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1202 Fix index name bug
  pymilvus/client/configs.py
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
  pymilvus/orm/index.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1205 Pop index_name even if it is empty
  pymilvus/orm/collection.py
  pymilvus/orm/index.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, dco-passed

#1206 Pop index_name in index param
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1203 Fix unable to connect to secure server after add
  pymilvus/orm/connections.py
  tests/test_connections.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1207 Fix prepare for properties
  pymilvus/client/prepare.py
  tests/test_prepare.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, dco-passed

#1208 Fix bug for example
  examples/collection.py
  examples/example.py
  pymilvus/orm/index.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1209 Fix unable to connect after add connection
  pymilvus/__init__.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1210 Update index interface
  examples/example.py
  examples/example_index.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
  pymilvus/orm/index.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1212 Don't raise exception when index is not exist
  pymilvus/orm/collection.py
  pymilvus/orm/index.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed
