Repository milvus-io/pymilvus, pull requests merged in 2022-06, with the labels that each got.

#1023 Enable sphinxcontrib-napoleon in sphnix docs
  docs/source/conf.py
  requirements.txt
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1024 Alter varChar type params's name to max_length
  examples/example_str.py
  examples/old_style_example_str.py
  pymilvus/client/configs.py
  pymilvus/orm/constants.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1026 Supprot index_name for get_index_state
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1004 support one-way authentication
  examples/cert/server.pem
  examples/example_tls1.py
  examples/example_tls2.py
  pymilvus/client/grpc_handler.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, kind/feature, size/L, ci-passed, PR | cherry-pick to 2.0, dco-passed

#1029 add listaliases and Collection.aliases (#1027)
  pymilvus/orm/collection.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1033 Extend grpcio version requirements range
  README.md
  requirements.txt
  setup.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-pick to 2.0, dco-passed

#1034 Reduce calls to describe_collection to speed up
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1037 Revert "Add ut for schema creation (#1021)"
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/types.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/constants.py
  pymilvus/orm/schema.py
  tests/test_grpc_handler.py
  tests/test_prepare.py
  tests/test_schema.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1038 Numpy example for bulkload
  examples/example_bulkload.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1040 Test L1 cases in nightly
  .github/workflows/nightly_ci.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1039 Enable index_name and disable field_name
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1041 Use warning instead of error to print log during retry
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
  tests/pytest.ini
  tests/test_grpc_handler.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1042 Fix the wrong function name in the error_handler
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
  tests/test_grpc_handler.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1043 Add more ut for decorators
  pymilvus/decorators.py
  tests/test_decorators.py
  tests/test_grpc_handler.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1044 Disable bulkload interfaces
  examples/example_bulkload.py
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1047 Fix nightly failure
  .github/workflows/nightly_ci.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1050 Enable to connect with uri and address
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/orm/connections.py
  tests/test_check.py
  tests/test_connections.py
  tests/test_grpc_handler.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1045 Fix loading_progress problems with partitions
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1052 Add ut for add_connection
  pymilvus/orm/connections.py
  tests/test_connections.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1057 Fix exception error code 0
  pymilvus/orm/connections.py
  tests/test_connections.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed
