Repository milvus-io/pymilvus, pull requests merged in 2022-02, with the labels that each got.

#874 Fix documentation url.
  README.md
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#879 Fix partition unable to delete bug
  docs/source/api/partition.rst
  pymilvus/orm/partition.py
Labels: kind/bug, approved, lgtm, ci-passed, PR | cherry-pick to 2.0

#883 Support secure gRPC channel for AWS
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
Labels: approved, lgtm, size/S, ci-passed

#886 Update FAQ based on user's report
  docs/source/faq.rst
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.0

#887 Fix string consistency level not work
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed

#889 Speed up pack operation on float vector
  pymilvus/client/blob.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.0

#891 Speed up pack opertation on float vector
  pymilvus/client/blob.py
Labels: approved, size/XS

#893 Change the doc version to 2.0.1
  docs/source/conf.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.0

#894 Support secure gRPC channel for AWS (#883)
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
Labels: PR | cherry-pick, approved, lgtm, size/S, ci-passed

#895 Update FAQ based on user's report (#886)
  docs/source/faq.rst
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#896 Fix string consistency level not work (#887)
  pymilvus/client/grpc_handler.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#897 Speed up pack operation on float vector (#889)
  pymilvus/client/blob.py
  pymilvus/client/prepare.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#898 Change the doc version to 2.0.1 (#893)
  docs/source/conf.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed

#901 Update approvers and reviewers in OWNERS file
  OWNERS
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.0

#899 Fix create_partition doc string
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: documentation, approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.0

#902 Fix loading progress output
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed, PR | cherry-pick to 2.0

#900 Fix readme bug
  README.md
Labels: documentation, approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.0

#904 Add support for numpy.ndarray for vector field
  examples/hello_milvus.ipynb
  examples/hello_milvus.py
  pymilvus/orm/prepare.py
Labels: approved, lgtm, size/L, ci-passed, PR | cherry-pick to 2.0
