Repository milvus-io/pymilvus, pull requests merged in 2022-03, with the labels that each got.

#916 Support varChar data type
  pymilvus/client/prepare.py
  pymilvus/client/types.py
  pymilvus/grpc_gen/proto/schema.proto
  pymilvus/grpc_gen/schema_pb2.py
  pymilvus/orm/constants.py
  pymilvus/orm/exceptions.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/M, ci-passed

#917 Change pymilvus package name in perf branch
  .github/workflows/publish_dev_package.yml
  setup.py
Labels: approved, lgtm, size/XS, ci-passed

#918 turn up rpc limit
  pymilvus/client/configs.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/XS

#919 Fix pymilvus unable to download on python3.8
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
  requirements.txt
  setup.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-pick to 2.0

#920 Fix master branch unable to trigger pushlish package
  .github/workflows/publish_dev_package.yml
  setup.py
Labels: approved, lgtm, size/XS, ci-passed

#923 Change pymilvus package name in perf branch
  .github/workflows/publish_dev_package.yml
  setup.py
Labels: approved, lgtm, size/XS, ci-passed

#921 Fix mergify rules for python3.8
  .github/mergify.yml
Labels: approved, lgtm, ci-passed, PR | cherry-pick to 2.0

#924 Update proto in perf branch
  pymilvus/client/prepare.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/proto/milvus.proto
Labels: approved, lgtm, size/L, ci-passed

#925 Ignore check data schema
  pymilvus/orm/collection.py
Labels: size/XS

#927 Support create index for scalar field
  examples/example_multiple_index.py
  pymilvus/client/configs.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/proto/milvus.proto
  pymilvus/orm/collection.py
  pymilvus/orm/index.py
Labels: approved, lgtm, kind/feature, ci-passed, PR | cherry-pick to 2.0

#928 Remove load balance from doc
  docs/source/api/utility.rst
Labels: approved, lgtm, size/XS, ci-passed

#929 Remove load balance from doc (#928)
  docs/source/api/utility.rst
Labels: approved, lgtm, size/XS, ci-passed

#930 Fix index_name in Index.drop()
  pymilvus/orm/index.py
Labels: kind/bug, approved, lgtm, ci-passed, PR | cherry-pick to 2.0
