Repository milvus-io/pymilvus, pull requests merged in 2023-09, with the labels that each got.

#1668 Fix lint error
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/schema.py
  pyproject.toml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1669 [cherry-pick] Fix lint error
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1664 Bulkinsert writer
  examples/example_bulkwriter.py
  pymilvus/__init__.py
  pymilvus/bulk_writer/__init__.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_import.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1671 [cherry-pick] Bulkinsert writer
  examples/example_bulkwriter.py
  pymilvus/__init__.py
  pymilvus/bulk_writer/__init__.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_import.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1677 Pass segment ids when get flush state
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, dco-passed

#1682 while parse uri, overwrite the db_name with default
  pymilvus/orm/connections.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, dco-passed

#1683 while parse uri, overwrite the db_name with default
  pymilvus/orm/connections.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, dco-passed

#1673 bulkwriter sample read csv
  .gitignore
  examples/data/train_embeddings.csv
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1686 [cherry-pick] bulkwriter sample read csv
  .gitignore
  examples/data/train_embeddings.csv
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1687 Fix typo of bulkimport example
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1688 [cherry-pick] Fix typo of bulkimport example
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1690 Fix concurrent bug of bulkwriter
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1691 [cherry-pick] Fix concurrent bug of bulkwriter
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1692 Update grpcio version range
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1693 Update grpcio version range
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1698 Url check for bulk_import
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1699 Url check for bulk_import
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1700 Update 2.2.x readme
  README.md
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1701 Add db parameter in flush_all
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1704 Add github action for publish on release (#1695)
  .github/workflows/publish_on_release.yml
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1702 Enable ignored checker PYI024
  pymilvus/client/interceptor.py
  pyproject.toml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1703 Enable ignored checker PYI024
  pymilvus/client/interceptor.py
  pyproject.toml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1713 Fix pass extra param
  pymilvus/client/grpc_handler.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, dco-passed

#1716 fix conflict for ef and batch size
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1681 Support new DataType: Array
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
  pymilvus/client/prepare.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/orm/constants.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1696 Change error_code to code
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/decorators.py
  pymilvus/exceptions.py
  pymilvus/orm/mutation.py
  tests/test_create_collection.py
  tests/test_decorators.py
  tests/test_grpc_handler.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1718 Support numpy type value for bulkwriter
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_writer.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1721 [cherry-pick] Support numpy type value for bulkwriter
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_writer.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1712 support best_reduce(#1711)
  examples/iterator.py
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed
