Repository milvus-io/pymilvus, pull requests merged in 2023-10, with the labels that each got.

#1736 Fix INDEX_NOT_EXIST error code
  pymilvus/client/grpc_handler.py
  pymilvus/exceptions.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1727 Enhance search result
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/future.py
  pymilvus/orm/iterator.py
  pymilvus/orm/partition.py
  pymilvus/orm/search.py
  pyproject.toml
  tests/test_abstract.py
  tests/test_prepare.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#1740 Fix rename_collection will move collection to default db
  pymilvus/client/grpc_handler.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, dco-passed

#1732 Fix a typo
  examples/hello_milvus.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1742 Fix describe miss some params
  pymilvus/client/abstract.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, dco-passed

#1744 Fix orm SearchFuture bug
  pymilvus/orm/future.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1745 add judgement for isPrimary
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1748 Fix search result
  pymilvus/client/abstract.py
  pymilvus/orm/future.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1743 Add a lower bound for minio
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1750 Fix has_collection result with Milvus2.2
  pymilvus/client/grpc_handler.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1752 Improve the default db for the rbac
  pymilvus/orm/role.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1753 [Cherry-Pick]: Improve the default db for the rbac (#1752)
  pymilvus/orm/role.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1755 Revert "Fix describe miss some params (#1742)"
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1757 Fix api key
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1760 Change unimpleted log level to debug
  pymilvus/decorators.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1761 Change unimpleted log level to debug
  pymilvus/decorators.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed
