Repository milvus-io/pymilvus, pull requests merged in 2023-02, with the labels that each got.

#1277 Change default connection timeout to 10s
  pymilvus/client/grpc_handler.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, kind/feature, ci-passed, dco-passed

#1276 Change default connection timeout to 10s
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, kind/feature, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1279 adjust resouce group api
  examples/resource_group.py
  pymilvus/__init__.py
  pymilvus/orm/resource_group.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/L, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1280 [cherry-pick]adjust resource group api
  examples/resource_group.py
  pymilvus/__init__.py
  pymilvus/orm/resource_group.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1281 remove deprecated code
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1282 remove deprecated code
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1283 fix resource group info def
  examples/resource_group.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1284 fix resource group def
  examples/resource_group.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1288 Deprecated all orm functions and classes
  CHANGELOGS.md
  pymilvus/decorators.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/constants.py
  pymilvus/orm/index.py
  pymilvus/orm/partition.py
  pymilvus/orm/role.py
  pymilvus/orm/schema.py
  pymilvus/orm/utility.py
  pymilvus/settings.py
Labels: approved, lgtm, size/M, ci-passed

#1291 fix describe/list rg err msg
  examples/resource_group.py
  pymilvus/client/grpc_handler.py
  pymilvus/orm/default_config.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1292 Add framework of pymilvus.v2
  CHANGELOGS.md
  pymilvus/v2/__init__.py
  pymilvus/v2/apis.py
  pymilvus/v2/async_apis.py
  pymilvus/v2/grpc_handler.py
  pymilvus/v2/types.py
Labels: approved, lgtm, size/L, ci-passed

#1293 fix load collection
  examples/resource_group.py
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1294 Change default connect timeout to 10s
  pymilvus/orm/connections.py
  pymilvus/orm/default_config.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1296 Multi cherryp-pick to sync master and 2.2
  examples/resource_group.py
  pymilvus/__init__.py
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
  pymilvus/orm/connections.py
  pymilvus/orm/default_config.py
Labels: PR | cherry-pick, approved, lgtm, size/M, ci-passed, dco-passed

#1297 add param check
  pymilvus/client/check.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1300 Remove deprecation on orm
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/index.py
  pymilvus/orm/partition.py
  pymilvus/orm/role.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed

#1305 expose rg info in replica
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  tests/test_types.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1304 fix can't insert string == schema max len
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1303 Support upsert
  docs/source/api/collection.rst
  docs/source/api/partition.rst
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1307 expose rg info
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1286 Add ignore_growing option for query and search
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1309 Init GrpcHandlers
  pymilvus/aio/apis.py
  pymilvus/aio/grpc_handler.py
  pymilvus/decorators.py
  pymilvus/mix_in.py
  pymilvus/settings.py
  pymilvus/types.py
  pymilvus/utils.py
  pymilvus/v2/apis.py
  pymilvus/v2/grpc_handler.py
  tests/aio/async_examples.py
  tests/aio/test_async_apis.py
  tests/conftest.py
  tests/test_v2_apis.py
Labels: approved, lgtm, ci-passed, size/XL

#1310 refine rg api
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1312 Fix some error
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1311 sync rg changes
  examples/resource_group.py
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/types.py
  pymilvus/orm/utility.py
  tests/test_types.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1314 Add GPU index types
  pymilvus/client/check.py
  pymilvus/client/utils.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1313 [Cherry-Pick]Add ignore_growing option for query and search (#1286)
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1315 Add TypeChecker
  pymilvus/aio/grpc_handler.py
  pymilvus/utils.py
  pymilvus/v2/apis.py
  pymilvus/v2/grpc_handler.py
  tests/conftest.py
  tests/test_utils.py
  tests/test_v2_apis.py
Labels: approved, lgtm, size/L, ci-passed
