Repository milvus-io/pymilvus, pull requests merged in 2023-12, with the labels that each got.

#1805 fix: Fix compactibility of exception with Milvus 2.2.x
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/utils.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1807 fix: Fix check_status for create_alias func
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1810 support search group-by(#1809)
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1815 add limit for too large ef to avoid huge latency for iterator(#1814)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1819 Set default port to 443 with https scheme
  pymilvus/client/utils.py
  pymilvus/orm/connections.py
  tests/test_connections.py
  tests/test_utils.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1818 use custmized version
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/pull_request.yml
  README.md
  _version_helper.py
  pyproject.toml
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1822 [skip-e2e] Fix ci-pass condition
  .github/mergify.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1821 Enable actions on 2.3 branch
  .github/mergify.yml
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1824 fix exceeding width of search_iterator(#1823)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1825 cp: Fix 1823-2.3
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1759 add gpu_cagra index in pymilvus
  pymilvus/client/check.py
  pymilvus/client/utils.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1826 Enable to set retry times
  pymilvus/decorators.py
  tests/test_decorators.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1831 set reduce_stop_for_best for iterator by default(#1830)
  pymilvus/client/prepare.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1832 set reduce_stop_for_best for iterator by default(#1830)
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1833 feat: support alter index
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1834 Bulkwriter set row group for parquet
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1836 Bulkwriter set row group for parquet
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed
