Repository milvus-io/pymilvus, pull requests merged in 2023-11, with the labels that each got.

#1765 Convert the result to python basic types to enable json dumps
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1766 Convert the result to python basic types to enable json dumps
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1769 Remove unused code for milvus client
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1770 Remove unused code for milvus client
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1768 fix: load_state parameter type err
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1772 Add float16 Vector Approve
  examples/float16_example.py
  pymilvus/client/entity_helper.py
  pymilvus/client/types.py
  pymilvus/orm/schema.py
  tests/test_abstract.py
  tests/test_collection.py
  tests/test_create_collection.py
  tests/test_schema.py
  tests/test_types.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1776 Revert "Add float16 Vector Approve"
  examples/float16_example.py
  pymilvus/client/entity_helper.py
  pymilvus/client/types.py
  pymilvus/orm/schema.py
  tests/test_abstract.py
  tests/test_collection.py
  tests/test_create_collection.py
  tests/test_schema.py
  tests/test_types.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1777 Modify highlevel delete to not return any value
  examples/hello_milvus_simple.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1778 Refine highlevel delete code comments
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1779 Add filter parameter to delete
  examples/hello_milvus_delete.py
  pymilvus/exceptions.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1792 enhance: remove partition existance check
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1795 search iterator support range-search paramter(#1793)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1798 adjust metrics comparison
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1799 enhance search iterator extension
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1802 Fix connect timeout bug
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1803 Bulkwriter supports parquet
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, size/L, ci-passed, dco-passed
