Repository milvus-io/pymilvus, pull requests merged in 2023-06, with the labels that each got.

#1469 Do not set metric_type default value in search params
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1507 Check if db name is invalid type
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1508 Check if db name is invalid type (#1507)
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
Labels: kind/bug, PR | cherry-pick, approved, lgtm, size/S, ci-passed, dco-passed

#1510 Remove useless check function
  pymilvus/client/check.py
  tests/test_check.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1512 Remove useless check function (#1510)
  pymilvus/client/check.py
  tests/test_check.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1511 Do not set metric_type default value in search params (#1469)
  pymilvus/client/prepare.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1514 Pick query impl from master
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1520 fix doc link
  README.md
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1521 Refactor milvus_client (#1513)
  examples/hello_milvus_simple.py
  examples/hello_milvus_simple2.py
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
  pymilvus/milvus_client/defaults.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/milvus_client/milvus_client_tests.py
  pymilvus/orm/schema.py
  pymilvus/orm/search.py
Labels: kind/enhancement, approved, lgtm, size/XXL, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1527 Fix bugs: describe_collection return dict and query filter parameter
  pymilvus/client/abstract.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1526 Fix bugs: describe_collection and query filter parameter
  pymilvus/client/abstract.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1528 Fix bug: should check invalid primary field
  pymilvus/orm/schema.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, dco-passed

#1532 Fix bug: should check invalid primary field (#1528)
  pymilvus/orm/schema.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1536 Defer check_fields when use milvus_client
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1537 Support async refresh
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, kind/feature, size/S, ci-passed, dco-passed

#1539 Defer check_fields when use milvus_client (#1536)
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/schema.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1534 fix iterator params accepted is not consistent and cursor updation problem
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1541 Support Chinese in JSON
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/XS, kind/feature, ci-passed, dco-passed

#1542 Support Chinese in JSON (#1541)
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/XS, kind/feature, ci-passed, dco-passed

#1548 Fix numpy version in install requires
  setup.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1549 Fix numpy version in install requires
  setup.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1546 Refinement: print clearer indication of the valid URI
  examples/non_ascii_encode.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1517 Create partition with just collection name
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1552 create collection incase of no collection (#1517)
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1551 Fix range_filter and radius in param but don't set
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1547 correct radius judgement
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1556 Change setup.py to pyproject.toml
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/nightly_ci.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
  Makefile
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/common_pb2.pyi
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2.pyi
  pymilvus/grpc_gen/schema_pb2.py
  pymilvus/grpc_gen/schema_pb2.pyi
  pyproject.toml
  requirements.txt
  setup.py
Labels: PR | cherry-pick, approved, lgtm, size/XXL, ci-passed, dco-passed

#1557 Change setup.py to pyproject.toml
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
  Makefile
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/common_pb2.pyi
  pymilvus/grpc_gen/feder_pb2.py
  pymilvus/grpc_gen/feder_pb2.pyi
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2.pyi
  pymilvus/grpc_gen/schema_pb2.py
  pymilvus/grpc_gen/schema_pb2.pyi
  pyproject.toml
  requirements.txt
  setup.py
Labels: approved, lgtm, size/XXL, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1560 Enable user to set max_length for pk field of string type
  pymilvus/exceptions.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1561 Enable user to set max_length for pk field of string type
  pymilvus/exceptions.py
  pymilvus/milvus_client/milvus_client.py
Labels: PR | cherry-pick, approved, lgtm, size/S, ci-passed, dco-passed

#1562 Fix apeche software license classifier
  pyproject.toml
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, dco-passed

#1563 Fix apache software license classifier
  pyproject.toml
Labels: approved, size/XS, dco-passed

#1564 Fix apache software license classifier (#1563)
  pyproject.toml
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1558 Retry RPCError except for DEADLINE_EXCEEDED and UNIMPLEMENTED
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
  tests/test_decorators.py
  tests/test_grpc_handler.py
Labels: PR | cherry-pick to master, approved, lgtm, size/M, ci-passed, dco-passed

#1568 Retry RPCError except for DEADLINE_EXCEEDED
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
  tests/test_decorators.py
  tests/test_grpc_handler.py
Labels: PR | cherry-pick, approved, lgtm, size/M, ci-passed, dco-passed
