Repository milvus-io/pymilvus, pull requests merged in 2023-08, with the labels that each got.

#1632 Fix exception message
  pymilvus/client/grpc_handler.py
  pymilvus/orm/constants.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, dco-passed

#1633 Fix exception message (#1632)
  pymilvus/client/grpc_handler.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, dco-passed

#1635 Remove time travel params
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1641 Fixbug: should fill empty dict when using dyanmic field
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1642 Fixbug: should fill empty dict when using dynamic field
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1636 Remove unused index and metric_type check
  pymilvus/client/check.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1637 Remove unused index and metric_type check
  pymilvus/client/check.py
Labels: PR | cherry-pick, approved, lgtm, size/M, ci-passed, dco-passed

#1645 deep copy params to avoid reuse parameters(#26355)
  pymilvus/client/grpc_handler.py
  pymilvus/client/utils.py
  pymilvus/orm/iterator.py
  pymilvus/orm/schema.py
  pyproject.toml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1647 support None expr for QueryIterator(Milvus-issue-26357)
  pymilvus/orm/collection.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1649 complete docstring for `list_collections()`
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1638 Unmask dataframe field name mismatch error
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1646 Disable logger from polluting other modules
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1651 refine iterator params to differentiate limit for clients(#26358 #26397)
  examples/iterator.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1656 refine search iterator perf by radius probe(#26552)
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1657 Fix semver not match pep440
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1661 Revert support default value
  pymilvus/client/abstract.py
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed
