Repository milvus-io/pymilvus, pull requests merged in 2023-03, with the labels that each got.

#1317 Correct GPU index types
  pymilvus/client/check.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1322 fix check string max len (#1304)
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1323 Add RAFT GPU index types
  pymilvus/client/check.py
  pymilvus/client/utils.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1318 Add some APIs
  pymilvus/aio/apis.py
  pymilvus/v2/apis.py
  tests/conftest.py
  tests/test_v2_apis.py
Labels: approved, lgtm, ci-passed, size/XL

#1325 Fix collection schema mismatch entities
  pymilvus/client/utils.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1326 Fix collection schema mismatch entities (#1325)
  pymilvus/client/prepare.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, dco-passed

#1328 Fix possible KeyError if description is not set
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1333 Fix error message when insert mismatch datatypes
  pymilvus/orm/schema.py
  tests/test_schema.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1338 Fix broken link
  README.md
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1339 Multi cherry picks from master branch
  pymilvus/orm/schema.py
  tests/test_schema.py
Labels: PR | cherry-pick, approved, lgtm, size/M, ci-passed, dco-passed

#1341 Fix FlushAll timeout [pick#1340]
  pymilvus/client/grpc_handler.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1340 Fix FlushAll timeout
  pymilvus/client/grpc_handler.py
Labels: kind/bug, PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed
