Repository milvus-io/pymilvus, pull requests merged in 2023-07, with the labels that each got.

#1565 Change pylint to ruff and black
  .github/mergify.yml
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/nightly_ci.yml
  .github/workflows/pull_request.yml
  Makefile
  README.md
  pylint.conf
  pymilvus/__init__.py
  pymilvus/client/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/blob.py
  pymilvus/client/check.py
  pymilvus/client/constants.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/interceptor.py
  pymilvus/client/prepare.py
  pymilvus/client/singleton_utils.py
  pymilvus/client/stub.py
  pymilvus/client/ts_utils.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/decorators.py
  pymilvus/exceptions.py
  pymilvus/grpc_gen/__init__.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/constants.py
  pymilvus/orm/db.py
  pymilvus/orm/future.py
  pymilvus/orm/index.py
  pymilvus/orm/iterator.py
  pymilvus/orm/mutation.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pymilvus/orm/role.py
  pymilvus/orm/schema.py
  pymilvus/orm/search.py
  pymilvus/orm/types.py
  pymilvus/orm/utility.py
  pymilvus/settings.py
  pyproject.toml
  requirements.txt
  test_requirements.txt
  tests/test_schema.py
  tests/test_types.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#1567 Change pylint to ruff and black
  .github/mergify.yml
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/nightly_ci.yml
  .github/workflows/pull_request.yml
  Makefile
  README.md
  pylint.conf
  pymilvus/__init__.py
  pymilvus/client/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/blob.py
  pymilvus/client/check.py
  pymilvus/client/constants.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/interceptor.py
  pymilvus/client/prepare.py
  pymilvus/client/singleton_utils.py
  pymilvus/client/stub.py
  pymilvus/client/ts_utils.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/decorators.py
  pymilvus/exceptions.py
  pymilvus/grpc_gen/__init__.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/db.py
  pymilvus/orm/future.py
  pymilvus/orm/index.py
  pymilvus/orm/mutation.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pymilvus/orm/role.py
  pymilvus/orm/schema.py
  pymilvus/orm/search.py
  pymilvus/orm/types.py
  pymilvus/orm/utility.py
  pymilvus/settings.py
  pyproject.toml
  requirements.txt
  test_requirements.txt
  tests/test_prepare.py
  tests/test_schema.py
  tests/test_types.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#1573 Seperate insert with upsert
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/partition.py
  tests/test_prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1576 Create index brefore wait for completion (#1571)
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1578 Fix RowBatch not exsits
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1580 Revert "Create index brefore wait for completion"
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1579 Revert "Create index brefore wait for completion (#1571)"
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1581 Fix upsert pre_batch_check
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1584 Fix describe_collection failed when max_length set to non-varchar field
  pymilvus/client/abstract.py
  pymilvus/client/prepare.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, dco-passed

#1585 Fix describe_collection failed when max_length set to non-varchar field (#1584)
  pymilvus/client/abstract.py
  pymilvus/client/prepare.py
Labels: kind/bug, PR | cherry-pick, approved, lgtm, ci-passed, dco-passed

#1586 Fix bug: wrong function annotation
  pymilvus/milvus_client/milvus_client.py
Labels: kind/enhancement, approved, lgtm, size/XS, ci-passed, dco-passed

#1587 Fix bug: wrong function annotation
  pymilvus/milvus_client/milvus_client.py
Labels: kind/bug, kind/enhancement, PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1583 add autoID to varchar dataType
  pymilvus/exceptions.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1588 Add fast fail error code
  pymilvus/decorators.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1589 Fix upsert typo
  pymilvus/orm/collection.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1590 Fix auto_id=False insertion serror
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1591 Fix search ouput field BianryVector error
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1592 Fix SearchIterator init error
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1594 Fix pagination dosc of Search
  pymilvus/orm/collection.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1593 Fix pagination dosc of Search
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1595 Add fast fail error code (#1588)
  pymilvus/decorators.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1596 Fix import connections in db
  pymilvus/orm/db.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1597 Fix import connections in db
  pymilvus/orm/db.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1598 Increase the number of retry times and decrease the duration of sleep
  pymilvus/decorators.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1600 Increase the number of retry times and decrease the duration of sleep (#1598)
  pymilvus/decorators.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1605 Fix search ouput field BianryVector error (#1591)
  pymilvus/client/abstract.py
Labels: kind/bug, PR | cherry-pick, approved, lgtm, size/S, ci-passed, dco-passed

#1609 Donot retry on RESOURCE_EXHAUSTED
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1611 Update bulkinsert example
  examples/example_bulkinsert_json.py
  examples/example_bulkinsert_numpy.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1612 [cherry-pick] Update bulkinsert example
  examples/example_bulkinsert_json.py
  examples/example_bulkinsert_numpy.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1615 Fix rename collection raise cannot be None error
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/utility.py
Labels: PR | cherry-pick to master, approved, lgtm, size/S, ci-passed, dco-passed

#1613 Support offset in search param
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1614 Support offset in search param
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1620 Fix a bug of bulkinsert
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1621 [cherry-pick] Fix a bug of bulkinsert
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1618 AlterCollection use KeyValuePair.
  pymilvus/client/prepare.py
  tests/test_prepare.py
Labels: PR | cherry-pick to master, approved, lgtm, size/XS, ci-passed, dco-passed

#1624 AlterCollection use KeyValuePair. (#1618)
  pymilvus/client/prepare.py
  tests/test_prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1627 Fix no timeout for wait for flushed
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1628 Fix no timeout for wait for flushed
  pymilvus/client/grpc_handler.py
Labels: kind/bug, PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed
