Repository milvus-io/pymilvus, pull requests merged in 2023-04, with the labels that each got.

#1345 Support python3.11
  .github/workflows/code_checker.yml
  pymilvus/client/constants.py
  pymilvus/client/ts_utils.py
  pymilvus/client/types.py
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/common_pb2.pyi
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2.pyi
  pymilvus/grpc_gen/python_gen.sh
  pymilvus/grpc_gen/schema_pb2.py
  pymilvus/grpc_gen/schema_pb2.pyi
  requirements.txt
  setup.py
  tests/test_types.py
Labels: PR | cherry-pick, approved, lgtm, size/XXL, ci-passed, dco-passed

#1346 Update supported index types
  pymilvus/client/check.py
  pymilvus/client/utils.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1348 Fix publish dev packge to testpypi action
  .github/workflows/publish_dev_package.yml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1349 Fix publish dev packge to testpypi action
  .github/workflows/publish_dev_package.yml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1352 Fix print too many nodeIDs of Replica
  pymilvus/client/types.py
  tests/test_types.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1362 Print all output fields
  pymilvus/client/abstract.py
  pymilvus/orm/search.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1363 Print all output fields (#1362)
  pymilvus/client/abstract.py
  pymilvus/orm/search.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1351 Fix print too many nodeIDs of Replica
  pymilvus/client/types.py
  tests/test_types.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1355 Multi cherry-picks of 2.2
  pymilvus/grpc_gen/python_gen.sh
  setup.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1343 Search could get ignore_growing option from kwargs
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1365 Search could get ignore_growing option from kwargs (#1343)
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1376 Add new metric type COSINE
  pymilvus/client/check.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1381 Add an utility to get server type
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/client/utils.py
  pymilvus/orm/utility.py
  tests/test_utils.py
Labels: approved, lgtm, kind/feature, size/M, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1382 Add an utility to get server type (#1381)
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/client/utils.py
  pymilvus/orm/utility.py
  tests/test_utils.py
Labels: PR | cherry-pick, approved, lgtm, kind/feature, size/M, ci-passed, dco-passed

#1384 Add support for setting uri from environment
  .env.example
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/configs.py
  pymilvus/client/constants.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/default_config.py
  pymilvus/orm/index.py
  pymilvus/settings.py
  requirements.txt
  setup.py
  tests/test_connections.py
  tests/test_prepare.py
Labels: PR | cherry-pick, approved, lgtm, size/L, ci-passed, dco-passed

#1383 Add support for setting uri from environment
  .env.example
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/configs.py
  pymilvus/client/constants.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  pymilvus/orm/default_config.py
  pymilvus/orm/index.py
  pymilvus/settings.py
  requirements.txt
  setup.py
  tests/test_connections.py
  tests/test_prepare.py
Labels: approved, lgtm, size/L, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1366 Enable github actions to test dependency
  .github/workflows/pull_request.yml
  test_requirements.txt
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1367 Enable github actions to test dependency
  .github/workflows/pull_request.yml
  test_requirements.txt
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1386 List indexes by field name
  pymilvus/orm/utility.py
Labels: approved, lgtm, kind/feature, size/M, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1390 List indexes by field name (#1386)
  pymilvus/orm/utility.py
Labels: PR | cherry-pick, approved, lgtm, kind/feature, size/M, ci-passed, dco-passed

#1388 Remove default of shards_num for new collection
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
  pymilvus/settings.py
Labels: PR | cherry-pick, approved, lgtm, size/M, ci-passed, dco-passed

#1387 Remove default of shards_num for new collection
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
  pymilvus/settings.py
Labels: approved, lgtm, size/M, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1391 Fix typo in config
  pymilvus/settings.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1394 Fix incorrect dim error msg
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1397 Fix get_server_type
  pymilvus/client/grpc_handler.py
  pymilvus/client/utils.py
  tests/test_utils.py
Labels: kind/bug, approved, lgtm, size/M, ci-passed, dco-passed

#1398 Fix get_server_type (#1397)
  pymilvus/client/grpc_handler.py
  pymilvus/client/utils.py
  tests/test_utils.py
Labels: kind/bug, approved, lgtm, size/M, ci-passed, dco-passed

#1400 Add param check for shards_num
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1402 Add param check for shards_num
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1405 Sync partiton APIs with collection
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1406 Sync partiton APIs with collection
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1374 Milvus Client
  pymilvus/milvus_client/__init__.py
  pymilvus/milvus_client/defaults.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/milvus_client/milvus_client_tests.py
  requirements.txt
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#1407 Multi cherry picks from master
  pymilvus/client/prepare.py
  pymilvus/milvus_client/__init__.py
  pymilvus/milvus_client/defaults.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/milvus_client/milvus_client_tests.py
  requirements.txt
Labels: PR | cherry-pick, approved, lgtm, size/XXL, ci-passed, dco-passed
