Repository milvus-io/pymilvus, pull requests merged in 2023-05, with the labels that each got.

#1409 Add num_shards property in Collection
  pymilvus/client/abstract.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1410 Add num_shards property in Collection
  pymilvus/client/abstract.py
  pymilvus/orm/collection.py
Labels: PR | cherry-pick, approved, lgtm, ci-passed, dco-passed

#1417 Remove unnecessary index check
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1418 Remove unnecessary index check (#1417)
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1408 Few fixes before 2.2.8 cherrypick
  pymilvus/__init__.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1420 Using database by URI
  examples/database.py
  pymilvus/client/grpc_handler.py
  pymilvus/orm/connections.py
  tests/test_connections.py
Labels: PR | cherry-pick to master, approved, lgtm, size/S, ci-passed, dco-passed

#1426 Support insert dict as JSON (#1424)
  pymilvus/client/entity_helper.py
  pymilvus/client/types.py
  pymilvus/orm/types.py
Labels: PR | cherry-pick, approved, lgtm, kind/feature, size/S, ci-passed, dco-passed

#1432 Fix lost JSON result
  pymilvus/client/abstract.py
  pymilvus/client/grpc_handler.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1433 Fix failed to calculate the length of JSON data
  pymilvus/client/utils.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1435 Fix convert all JSON data to results for each entity
  pymilvus/client/grpc_handler.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1436 Update only one field message
  pymilvus/exceptions.py
  pymilvus/orm/schema.py
Labels: PR | cherry-pick to master, approved, lgtm, size/XS, ci-passed, dco-passed

#1437 Fix num_partitions type
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1438 Fix num_partitions type
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1443 Fix None user/password
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1431 support iterator for query and search
  examples/iterator.py
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1444 Support Default Value
  pymilvus/client/abstract.py
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1448 [Cherry-Pick] Fix JSON related bugs
  pymilvus/client/abstract.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/utils.py
Labels: kind/bug, PR | cherry-pick, approved, lgtm, size/S, ci-passed, dco-passed

#1445 deduce secure from user/pass
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1428 adding distance metric selection
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1412 Unify num_shards and mark shards_num as deprecated
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
  tests/test_prepare.py
Labels: approved, lgtm, size/M, ci-passed, PR | cherry-pick to 2.2, dco-passed

#1451 Fix default value appear when not set
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1452 Multi cherry-picks from master branch
  pymilvus/__init__.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
  pymilvus/orm/connections.py
  tests/test_prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1453 Multi cherry from 2.2 to master
  examples/database.py
  examples/role_and_privilege.py
  pymilvus/__init__.py
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/types.py
  pymilvus/orm/connections.py
  pymilvus/orm/db.py
  pymilvus/orm/role.py
  tests/test_connections.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1455 Fix wait for channel ready error
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1456 Fix wait for channel ready error
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1457 Fix calling on closed channel
  pymilvus/client/grpc_handler.py
Labels: PR | cherry-pick to master, approved, lgtm, size/XS, ci-passed, dco-passed

#1459 Fix calling on closed channel (#1457)
  pymilvus/client/grpc_handler.py
Labels: PR | cherry-pick, approved, size/XS, ci-passed, dco-passed

#1468 Fix bug for insert rows when enable auto_id
  pymilvus/client/prepare.py
  tests/test_prepare.py
Labels: kind/bug, approved, lgtm, size/M, ci-passed, dco-passed

#1467 Fix bug for insert rows when enable auto_id
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
  tests/test_prepare.py
Labels: kind/bug, approved, lgtm, size/M, ci-passed, dco-passed

#1462 Fix default value store in unknow dataType
  pymilvus/client/abstract.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1471 Auto set secure=True for https scheme
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1470 Auto set secure=True for https scheme
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1460 Support api key
  pymilvus/client/grpc_handler.py
  pymilvus/client/interceptor.py
  pymilvus/client/utils.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1465 Set auto_id default value False
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1466 Set auto_id default value False
  pymilvus/orm/schema.py
Labels: PR | cherry-pick, approved, lgtm, size/M, ci-passed, dco-passed

#1474 Revert remove auto_id in collection schema
  pymilvus/client/grpc_handler.py
  pymilvus/orm/schema.py
  tests/test_grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1475 Revert remove auto_id in collection schema
  pymilvus/orm/schema.py
  tests/test_grpc_handler.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1472 Support api key (#1460)
  pymilvus/client/grpc_handler.py
  pymilvus/client/interceptor.py
  pymilvus/client/utils.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1480 Fix fetch latest numpy
  .github/workflows/check_milvus_proto.yml
  setup.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1483 Fix fetch latest numpy
  .github/workflows/check_milvus_proto.yml
  setup.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1473 Make default value set None valid
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1481 Backward compatibility logic for Connect
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1482 Backward compatibility logic for Connect (#1481)
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1484 Call Connect after db name changed
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1485 Call Connect after db name changed (#1484)
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1486 Remind users when unimplemented feature was called
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1491 Fix bug: failed to insert binary vector
  examples/binary_example.py
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1490 Fix bug for insert binary vectors by rows
  examples/binary_example.py
  pymilvus/client/entity_helper.py
Labels: kind/bug, approved, lgtm, size/M, ci-passed, dco-passed

#1494 Pass the is_dynamic field to the milvus server
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1496 Fix check DB available failed
  pymilvus/orm/connections.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, PR | cherry-picked to 2.2, dco-passed

#1497 Fix check DB available failedFix bug: failed to check invalid db due to broken parameter ordering
  pymilvus/orm/connections.py
Labels: kind/bug, PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1495 Pass the is_dynamic field to the milvus server
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1499 Fix insert hangs when insert more fields than schema defined
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1502 Fix typo
  pymilvus/client/grpc_handler.py
Labels: kind/bug, approved, lgtm, size/XS, ci-passed, dco-passed
