Repository milvus-io/pymilvus, pull requests merged in 2024-10, with the labels that each got.

#2272 fix: not put 'default_value' in dict
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2275 fix not check None Type in json and support no need to pass in None when insert row
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
  tests/test_prepare.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2273 remove analyzer_params, added enable_tokenizer and tokenizer_params
  pymilvus/orm/constants.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2192 feat(pymilvus/settings.py): Load configuration without altering the environment
  pymilvus/settings.py
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2286 fix: upsert rows when set autoid==true fail
  pymilvus/client/prepare.py
  tests/test_prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2287 fix: upsert rows when set autoid==true fail(#2286)
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/decorators.py
  pymilvus/orm/collection.py
  pymilvus/orm/schema.py
  pymilvus/orm/utility.py
  tests/test_prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2257 support new Function feature
  examples/hello_bm25.py
  examples/hello_hybrid_bm25.py
  examples/milvus_client/bm25.py
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/check.py
  pymilvus/client/prepare.py
  pymilvus/client/types.py
  pymilvus/exceptions.py
  pymilvus/orm/constants.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#2245 Upgrade the bulkWriter cloud API call from v1 to v2
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2246 [cherry-pick] Upgrade the bulkWriter cloud API call from v1 to v2
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2291 feat: allow empty sparse row
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2293 fix: reset offset to zero after seek(#2292)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2294 fix: remove duplicate field name check in pymilvus
  pymilvus/exceptions.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2297 enhance: enable compatible for iterator(#2278)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2295 enhance: Enable bulkwriter to support import v2
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2296 enhance: Enable bulkwriter to support import v2 (#2295)
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2298 fix: row based insert/upsert when there is Function in schema
  pymilvus/client/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2290 Improve embedding retrieval performance
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2300 Improve embedding retrieval performance
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2301 fix: add BM25 to supported metric type of search iterator
  examples/hello_hybrid_bm25.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2303 fix: simplified the logic to check if the insert/request data matches the schema
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2304 fix: Passing messages to code in ParamError
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2305 fix: Passing messages to code in ParamError (#2304)
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2281 fix: Fix the f16 and bf16 dump error & add all type test for csv & csv supports null
  examples/example_bulkinsert_csv.py
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2307 enhance: handling cp file for query iterator(#2306)
  examples/iterator.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2310 enhance: handling abormal iterator cp file(#2306)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2309 fix: entity_is_sparse_matrix: each row should be dict or list
  pymilvus/client/entity_helper.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2302 Fixed typo in comment of step 1
  examples/hello_milvus.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed
