Repository milvus-io/pymilvus, pull requests merged in 2024-03, with the labels that each got.

#1936 enhance: ban iteration and range search for groupBy(#1935)
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1915 enhance: change connection timeout to clearer msg
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#1944 milvus client insert to return ids as well
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1943 collection.insert to return connection insert result directly
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1946 Revert "collection.insert to return connection insert result directly"
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1948 Fix several bugs reated to MilvusClient
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1947 collection.insert to return connection insert result directly
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1941 fix: Donot retry on UnImplemented
  pymilvus/decorators.py
  tests/test_decorators.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#1942 fix: Donot retry on UnImplemented
  pymilvus/decorators.py
  tests/test_decorators.py
Labels: PR | cherry-pick, approved, lgtm, ci-passed, dco-passed

#1945 enhance: Add issue template for enhancemant
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/enhancement.yaml
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/ISSUE_TEMPLATE/general-question.yaml
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1949 Fix bug: add enable_dynamic_field in result of DescribeCollection
  pymilvus/client/abstract.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.x, dco-passed

#1916 enhance: [cherry-pick]change connection timeout to clearer msg
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/orm/connections.py
Labels: PR | cherry-pick, approved, lgtm, size/S, ci-passed, dco-passed

#1954 Avoiding parameter conflicts and add compatibility logic
  examples/milvus_client/customize_schema_auto_id.py
  examples/milvus_client/non_ascii_encode.py
  examples/milvus_client/rbac.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/milvus_client/index.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1955 Fix a small bug of bulkwriter
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1956 Fix a small bug of bulkwriter
  pymilvus/bulk_writer/bulk_writer.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1957 pick MilvusClient from master
  examples/hello_milvus_simple.py
  examples/hello_milvus_simple2.py
  examples/milvus_client/alias.py
  examples/milvus_client/customize_schema.py
  examples/milvus_client/customize_schema_auto_id.py
  examples/milvus_client/index.py
  examples/milvus_client/non_ascii_encode.py
  examples/milvus_client/partition.py
  examples/milvus_client/rbac.py
  examples/milvus_client/simple.py
  examples/milvus_client/simple_auto_id.py
  pymilvus/client/abstract.py
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/types.py
  pymilvus/exceptions.py
  pymilvus/milvus_client/check.py
  pymilvus/milvus_client/index.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/schema.py
Labels: kind/enhancement, approved, lgtm, size/XXL, ci-passed, dco-passed

#1959 fix: rename_collection not apply in current db
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.x, dco-passed

#1963 Import and add example of IndexParams
  examples/milvus_client/index_params.py
  pymilvus/__init__.py
  pymilvus/milvus_client/__init__.py
Labels: kind/enhancement, approved, lgtm, size/S, ci-passed, dco-passed

#1964 Import and add example of IndexParams
  examples/milvus_client/index_params.py
  pymilvus/__init__.py
  pymilvus/milvus_client/__init__.py
  pymilvus/milvus_client/milvus_client.py
Labels: kind/enhancement, approved, lgtm, size/S, ci-passed, dco-passed

#1965 Fix idempotence of Collection
  pymilvus/client/abstract.py
  pymilvus/orm/schema.py
Labels: kind/bug, approved, lgtm, size/S, ci-passed, dco-passed

#1966 Fix idempotence of Collection
  pymilvus/client/abstract.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1967 Refine some comments related to MilvusClient
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1968 Refine some comments related to MilvusClient
  pymilvus/milvus_client/milvus_client.py
Labels: kind/enhancement, PR | cherry-pick, approved, lgtm, size/S, ci-passed, dco-passed

#1969 Support clustering key in create collection
  pymilvus/client/abstract.py
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1902 feat: Add sparse float vector support to PyMilvus
  examples/hello_sparse.py
  examples/milvus_client/sparse.py
  pymilvus/client/abstract.py
  pymilvus/client/check.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/iterator.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
  pymilvus/orm/types.py
  requirements.txt
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1961 fix: rename_collection not apply in current db(#1959)
  pymilvus/orm/utility.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1971 Add embedding models to pymilvus.
  examples/hello_model.py
  pymilvus/model/__init__.py
  pymilvus/model/base.py
  pymilvus/model/dense/__init__.py
  pymilvus/model/dense/openai.py
  pymilvus/model/dense/sentence_transformer.py
  pymilvus/model/hybrid/__init__.py
  pymilvus/model/hybrid/bge_m3.py
  pymilvus/model/sparse/__init__.py
  pymilvus/model/sparse/bm25/__init__.py
  pymilvus/model/sparse/bm25/bm25.py
  pymilvus/model/sparse/bm25/lang.yaml
  pymilvus/model/sparse/bm25/tokenizers.py
  pymilvus/model/sparse/splade.py
  pyproject.toml
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#1972 Change the sparse embedding from List[csr_array] to csr_array
  pymilvus/model/hybrid/bge_m3.py
  pymilvus/model/sparse/bm25/bm25.py
  pymilvus/model/sparse/splade.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1973 sparse float vector: do not infer empty list as sparse vector input
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1975 enhance: retry on inconsistent requery
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1976 enhance: retry on inconsistent requery (#1975)
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1977 fix: Update versions in readme to latest
  README.md
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#1978 fix: [cherry-pick]Update versions in readme to latest
  README.md
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1981 fix: [cherry-pick]Remove the dependency of server_name to others
  pymilvus/client/grpc_handler.py
Labels: PR | cherry-pick, approved, lgtm, size/M, ci-passed, dco-passed

#1983 Add gpu index examples:cagra and brute froce
  examples/example_gpu_brute_force.py
  examples/example_gpu_cagra.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1980 fix: Remove the dependency of server_name to others
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#1985 enhance: add example for fuzzy matching
  examples/fuzzy_match.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1986 Decouple model lib from pymilvus main repo.
  pymilvus/model/__init__.py
  pymilvus/model/base.py
  pymilvus/model/dense/__init__.py
  pymilvus/model/dense/openai.py
  pymilvus/model/dense/sentence_transformer.py
  pymilvus/model/hybrid/__init__.py
  pymilvus/model/hybrid/bge_m3.py
  pymilvus/model/sparse/__init__.py
  pymilvus/model/sparse/bm25/__init__.py
  pymilvus/model/sparse/bm25/bm25.py
  pymilvus/model/sparse/bm25/lang.yaml
  pymilvus/model/sparse/bm25/tokenizers.py
  pymilvus/model/sparse/splade.py
  pyproject.toml
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#1989 enhance: add example for hybrid search
  examples/hybrid_search.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1990 Added a simple example of performing sparse dense hybrid search
  examples/hello_hybrid_sparse_dense.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1991 fix: example of float16
  examples/bfloat16_example.py
  examples/float16_example.py
Labels: approved, size/XS, dco-passed

#1993 Fix float16_example and bfloat16_example
  examples/bfloat16_example.py
  examples/float16_example.py
Labels: approved, size/XS, dco-passed

#1994 add warning about gpu example
  examples/example_gpu_brute_force.py
  examples/example_gpu_cagra.py
Labels: approved, size/S, dco-passed

#1995 Add friendly setup instructions to hello_hybrid_sparse_dense.py
  examples/hello_hybrid_sparse_dense.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-pick to 2.x, dco-passed

#1996 enhance: tidy dependencies in tests
  .github/workflows/pull_request.yml
  README.md
  examples/bfloat16_example.py
  examples/collection.py
  examples/partition.py
  examples/role_and_privilege.py
  pyproject.toml
  requirements.txt
  test_requirements.txt
  tests/test_connections.py
  tests/test_types.py
  tests/utils.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1997 enhance: [cherry-pick]tidy dependencies in tests
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/nightly_ci.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
  README.md
  examples/collection.py
  examples/partition.py
  examples/role_and_privilege.py
  pyproject.toml
  requirements.txt
  test_requirements.txt
  tests/test_connections.py
  tests/test_types.py
  tests/utils.py
Labels: PR | cherry-pick, approved, lgtm, size/L, ci-passed, dco-passed
