Repository milvus-io/pymilvus, pull requests merged in 2024-04, with the labels that each got.

#2011 fix: Use wrong placeholder type for bf16 and float16
  examples/bfloat16_example.py
  examples/float16_example.py
  pymilvus/client/blob.py
  pymilvus/client/entity_helper.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/orm/prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2012 fix: [cherry-pick]Use wrong placeholder type for bf16 and float16
  examples/bfloat16_example.py
  examples/float16_example.py
  pymilvus/client/blob.py
  pymilvus/client/entity_helper.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/orm/prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2022 covert params' value from string to int
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2026 [cherry-pick] covert params' value from string to int
  pymilvus/orm/schema.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#2025 fix: restrict input/search type for vector fields
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/orm/collection.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
  pyproject.toml
Labels: approved, lgtm, size/L, ci-passed, PR | cherry-pick to 2.x, dco-passed

#2023 Support UDS
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/XS, ci-passed, PR | cherry-pick to 2.x, dco-passed

#2028 enhance: Update hello_hybrid_sparse_dense.py example to include BGE reranker
  examples/hello_hybrid_sparse_dense.py
Labels: approved, lgtm, size/M, ci-passed, PR | cherry-pick to 2.x, dco-passed

#2029 fix: [cherry-pick]restrict input/search type for vector fields (#2025)
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/orm/collection.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
  pyproject.toml
Labels: PR | cherry-pick, approved, lgtm, size/L, ci-passed, dco-passed

#2032 enhance: [2.4] Update hello_hybrid_sparse_dense.py example to include BGE reranker
  examples/hello_hybrid_sparse_dense.py
Labels: PR | cherry-pick, approved, lgtm, size/M, ci-passed, dco-passed

#2031 use reranker ignoring usage of bge m3
  examples/hello_hybrid_sparse_dense.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-pick to 2.x, dco-passed

#2038 Revert "enhance: retry on inconsistent requery"
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed, needs-dco

#2039 Revert "enhance: retry on inconsistent requery (#1975)"
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed, needs-dco

#2035 fix: Fix import array via bulkwriter
  pymilvus/bulk_writer/buffer.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2036 fix: Fix import array via bulkwriter (#2035)
  pymilvus/bulk_writer/buffer.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2048 fix: Remove np.view for floatvector
  examples/hello_milvus.py
  pymilvus/client/entity_helper.py
  pymilvus/orm/prepare.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2049 fix: Remove np.view for floatvector
  examples/hello_milvus.py
  pymilvus/client/entity_helper.py
  pymilvus/orm/prepare.py
Labels: PR | cherry-pick, approved, lgtm, size/S, ci-passed, dco-passed

#2051 fix: pass offset parameter for hybrid search to server
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2052 fix: pass offset parameter for hybrid search to server
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2055 support the report value in the dml and dql request
  examples/hello_cost.py
  examples/milvus_client/simple_cost.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/mutation.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed
