Repository milvus-io/pymilvus, pull requests merged in 2024-02, with the labels that each got.

#1907 Fix bug for insert ndarray in json field
  pymilvus/client/entity_helper.py
  pymilvus/exceptions.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#1909 Fix bug for insert ndarray in json field
  pymilvus/client/entity_helper.py
  pymilvus/exceptions.py
Labels: PR | cherry-pick, approved, lgtm, size/S, ci-passed, dco-passed

#1913 enhance: upgrade ruff and coding styles
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/ts_utils.py
  pymilvus/orm/collection.py
  pymilvus/orm/iterator.py
  pymilvus/orm/schema.py
  pyproject.toml
  requirements.txt
  test_requirements.txt
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#1912 Fix several bugs related to MilvusClient
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/check.py
  pymilvus/milvus_client/index.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1914 enhance: [cherry-pick]upgrade ruff and coding styles
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/ts_utils.py
  pymilvus/orm/collection.py
  pymilvus/orm/iterator.py
  pymilvus/orm/schema.py
  pyproject.toml
  requirements.txt
  test_requirements.txt
Labels: PR | cherry-pick, approved, lgtm, size/M, ci-passed, dco-passed

#1917 fix:the length of fields data is not consistence when fp16/bf16 vectors as query output fields
  pymilvus/client/utils.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1919 Add list_aliases and describe_alias
  examples/milvus_client/alias.py
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1920 Fix several bugs related to MilvusClient
  examples/milvus_client/index.py
  pymilvus/milvus_client/index.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1923 Fix several bugs related to MilvusClient
  pymilvus/client/grpc_handler.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1924 fix: can't get vector when fp16/bf16 vectors as output fields
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
  pymilvus/client/utils.py
  pymilvus/orm/schema.py
  tests/test_abstract.py
  tests/test_collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1932 fix alter_index response
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1934 ci: Update actions
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/nightly_ci.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/publish_on_release.yml
  .github/workflows/pull_request.yml
Labels: approved, lgtm, size/S, ci-passed, dco-passed
