Repository milvus-io/pymilvus, pull requests merged in 2024-01, with the labels that each got.

#1829 Support delete with consistency level
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1827 [cherry-pick] Enable to set retry times
  pymilvus/decorators.py
  tests/test_decorators.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1845 Auto reconnection when channel state changed to idle
  pymilvus/client/grpc_handler.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1846 Auto reconnection when channel state changed to idle
  pymilvus/client/grpc_handler.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1851 fix: Fix bug for add connection when url is https
  pymilvus/orm/connections.py
  tests/test_connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1852 fix: Fix bug for add connection when url is https
  pymilvus/orm/connections.py
  tests/test_connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#1854 enchance: refine group_by_field and provide group_by example(#1809)
  examples/example_group_by.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1837 Add new gpu index GPU_BRUTE_FORCE
  pymilvus/client/utils.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1855 fix: to avoid zero value for width
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1857 Add float16 and bfloat16 approve
  examples/bfloat16_example.py
  examples/float16_example.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/orm/schema.py
  test_requirements.txt
  tests/test_abstract.py
  tests/test_collection.py
  tests/test_create_collection.py
  tests/test_schema.py
  tests/test_types.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1860 Support python3.12
  .github/mergify.yml
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/publish_on_release.yml
  .github/workflows/pull_request.yml
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/common_pb2.pyi
  pymilvus/grpc_gen/feder_pb2.py
  pymilvus/grpc_gen/feder_pb2.pyi
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2.pyi
  pymilvus/grpc_gen/msg_pb2.py
  pymilvus/grpc_gen/msg_pb2.pyi
  pymilvus/grpc_gen/schema_pb2.py
  pymilvus/grpc_gen/schema_pb2.pyi
  pyproject.toml
  requirements.txt
  test_requirements.txt
  tests/test_create_collection.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1861 [cherry-pick] Support python3.12
  .github/mergify.yml
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/publish_on_release.yml
  .github/workflows/pull_request.yml
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/common_pb2.pyi
  pymilvus/grpc_gen/feder_pb2.py
  pymilvus/grpc_gen/feder_pb2.pyi
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2.pyi
  pymilvus/grpc_gen/msg_pb2.py
  pymilvus/grpc_gen/msg_pb2.pyi
  pymilvus/grpc_gen/schema_pb2.py
  pymilvus/grpc_gen/schema_pb2.pyi
  pyproject.toml
  requirements.txt
  test_requirements.txt
  tests/test_create_collection.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#1862 fix: Use tf-nightly for python3.12 support
  test_requirements.txt
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1876 Change BulkWriter default parameters
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1877 Change BulkWriter default parameters
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#1881 fix: change confusing error message
  pymilvus/exceptions.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1874 adition index params for raft index
  pymilvus/client/utils.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#1890 Multi-cherry bug fixes from master
  pymilvus/exceptions.py
  pymilvus/orm/iterator.py
Labels: PR | cherry-pick, approved, lgtm, size/XS, ci-passed, dco-passed

#1904 BulkWriter supports Azure blob storage
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/remote_bulk_writer.py
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#1905 BulkWriter supports Azure blob storage
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/remote_bulk_writer.py
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, size/L, ci-passed, dco-passed
