Repository milvus-io/pymilvus, pull requests merged in 2024-11, with the labels that each got.

#2319 fix: bulkwriter to skip function output fields
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2323 enhance: Rename tokenizer_params to analyzer_params
  examples/hello_bm25.py
  examples/hello_hybrid_bm25.py
  examples/milvus_client/bm25.py
  pymilvus/orm/constants.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2326 feat: Add compact, get_server_version and flush api
  examples/milvus_client/compact.py
  examples/milvus_client/flush.py
  examples/milvus_client/get_server_version.py
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2329 modify strict_group_size parameter name(#2328)
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2330 Corrected grammar and consistency in error messages (#2289)
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2316 fix queryIterator question
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2333 Fix typo and correct grammar
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2337 Update return type of describe_role to Dict (#2332)
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2335 Add text embedding function
  examples/example_bulkinsert_withfunction.py
  examples/hello_text_embedding.py
  examples/milvus_client/text_embedding.py
  pymilvus/client/types.py
  pymilvus/exceptions.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#2321 [2.4]Use filter_params for milvus client
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2345 Remove unnecessary invoke of describe_collection()
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2357 fix: [2.4] add privilege group orm
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/role.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2356 fix: add privilege group orm
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/role.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2359 fix: Add upper limit for grpcio to 1.67.1
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2360 fix: Add upper limit for grpcio to 1.67.1
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2365 Correct grammar
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2366 fix: RBAC fix privilege group orm
  pymilvus/orm/role.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2367 fix: [2.4] RBAC fix privilege group orm
  pymilvus/orm/role.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2350 fix: cannot pass consistency level for delete
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  tests/test_prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2351 fix: cannot pass consistency level for delete
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  tests/test_prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2373 Add default values to Pop to prevent exceptions
  pymilvus/__init__.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/client/check.py
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2376 enhance: add bitmap index example
  examples/orm/bitmap_index_example.py
  examples/test_bitmap_index.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2372 enhance: format list privilege group result
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/role.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2377 enhance: Enhance log messages when Connect with server failed
  pymilvus/decorators.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2379 enhance: Prepare to release 2.5.0
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
  README.md
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2380 enhance: Prepare 2.4.10 release
  README.md
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2382 fix: when insert do not add function output field to dynamic field
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2384 fix: Branch 2.5 action rules
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/doc_update_event.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
  .github/workflows/release_event.yml
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2383 enhance: add examples for text match
  examples/orm/hello_text_match.py
  examples/text_match.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2385 fix: Master action trigger
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/pull_request.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2386 enhance: grant/revoke v2 optional db and collection params
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/role.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2392 enhance: [2.4] grant/revoke v2 optional db and collection params
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/role.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2393 enhance: [2.5] grant/revoke v2 optional db and collection params
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/role.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed
