Repository milvus-io/pymilvus, pull requests merged in 2024-05, with the labels that each got.

#2068 fix: Remove params for property vars
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/S, ci-passed, PR | cherry-pick to 2.x, dco-passed

#2015 feat: Support major compaction in ManualCompaction
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2066 Change sparse related errors to ParamError
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2070 [2.4] change sparse related errors to ParamError
  pymilvus/client/entity_helper.py
Labels: PR | cherry-pick, approved, lgtm, size/S, ci-passed, dco-passed

#2065 modified example_tls1.py through MilvusClient
  examples/example_tls1.py
Labels: approved, lgtm, size/L, ci-passed, PR | cherry-pick to 2.x, dco-passed

#2074 remove scipy dependency for sparse while still supporting scipy sparse matrix
  examples/hello_sparse.py
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/orm/collection.py
  pymilvus/orm/iterator.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2076 [2.4] remove scipy dependency for sparse while still supporting it
  examples/hello_sparse.py
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/orm/collection.py
  pymilvus/orm/iterator.py
  pymilvus/orm/partition.py
  pymilvus/orm/prepare.py
  pyproject.toml
  requirements.txt
Labels: PR | cherry-pick, approved, lgtm, size/L, ci-passed, dco-passed

#2077 modified example_tls2.py through MilvusClient
  examples/example_tls2.py
Labels: approved, lgtm, size/L, ci-passed, PR | cherry-pick to 2.x, dco-passed

#2085 enhance: Cherry pick #1949, #2065, #2077
  examples/example_tls1.py
  examples/example_tls2.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2086 enhance: Make bulk_writer's requirments optional
  examples/example_bulkwriter.py
  pymilvus/__init__.py
  pymilvus/bulk_writer/__init__.py
  pyproject.toml
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2087 enhance: [2.4]Make bulk_writer's requirments optional (#2086)
  examples/example_bulkwriter.py
  pymilvus/__init__.py
  pymilvus/bulk_writer/__init__.py
  pyproject.toml
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2088 fix: Revert of dup cherry-pick #1949
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2092 [2.4] support the report value in the dml and dql request
  examples/hello_cost.py
  examples/milvus_client/simple_cost.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/mutation.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2094 fix sparse: accpet int/float wrapped in string
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2096 enhance: [2.4]Expand grpcio version to latest
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/pull_request.yml
  Makefile
  README.md
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/feder_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/msg_pb2.py
  pymilvus/grpc_gen/python_gen.sh
  pymilvus/grpc_gen/rg_pb2.py
  pymilvus/grpc_gen/schema_pb2.py
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2093 enhance: Expand grpcio version to latest
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/pull_request.yml
  Makefile
  README.md
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/feder_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/msg_pb2.py
  pymilvus/grpc_gen/python_gen.sh
  pymilvus/grpc_gen/rg_pb2.py
  pymilvus/grpc_gen/schema_pb2.py
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2098 [2.4] fix the str function of the extra list
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2099 fix the str function of the extra list
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2090 Added grpc as a valid protocol for uri
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2104 feat: allowing search iterator on sparse float vector field
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2105 feat: [2.4] allowing search iterator on sparse float vector field
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed
