Repository milvus-io/pymilvus, pull requests merged in 2024-07, with the labels that each got.

#2158 fix: Coding style by latest ruff
  pymilvus/client/check.py
  pymilvus/client/types.py
  pymilvus/orm/collection.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2159 fix: Coding style by latest ruff
  pymilvus/client/check.py
  pymilvus/client/types.py
  pymilvus/orm/collection.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2163 enhance: Remove the logic to set replica_number=1 by default
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2164 Add database operations to MilvusClient (#2152)
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2167 enhance: Remove the logic to set replica_number=1 by default (#2163)
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2173 enhance: upsert support autoid
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2180 fix: Edit setuptools upper version for py380
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2182 fix: Edit setuptools upper version for py380
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2187 Fix comment in iterator implementation
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2183 enhance:expose reduce_stop_for_best to users(#2181)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2188 enhance:expose reduce_stop_for_best to users(#2181)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2190 Don't export rows info in index params
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2191 [cherry-pick] Don't export rows info in index params
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2194 fix: remove limitation clustering key can not be primary key
  pymilvus/exceptions.py
  pymilvus/orm/schema.py
  tests/test_create_collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2196 fix: [cherry-pick] remove limitation clustering key can not be primary key
  pymilvus/exceptions.py
  pymilvus/orm/schema.py
  tests/test_create_collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2200 enhance: hide zero values ​​when printing
  examples/milvus_client/simple_cost.py
  pymilvus/client/abstract.py
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2201 enhance: hide zero values ​​when printing
  examples/milvus_client/simple_cost.py
  pymilvus/client/abstract.py
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed
