Repository milvus-io/pymilvus, pull requests merged in 2024-09, with the labels that each got.

#2249 fix: move page_retain_order to the same level as radius
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  tests/test_prepare.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2250 fix: [2.4] move page_retain_order to the same level as radius
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  tests/test_prepare.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2254 add strict_group_size and rank_group_scorer for hybrid_search(#2253)
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2251 fix: not report error when setting default_value=None
  pymilvus/exceptions.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2247 enhance: Bulkinsert support csv
  examples/example_bulkinsert_csv.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2259 add hybrid_search for MilvusClient
  examples/hybrid_search.py
  examples/milvus_client/hybrid_search.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2256 feat: support keyword text match
  pymilvus/client/check.py
  pymilvus/client/prepare.py
  pymilvus/orm/constants.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2262 enhance: support print iterator info(#2261)
  examples/iterator.py
  pymilvus/client/prepare.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed
