Repository milvus-io/pymilvus, pull requests merged in 2024-08, with the labels that each got.

#2209 fix: [2.4]unclear error msg for varchar field
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2208 fix: unclear error msg for varchar field
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2216 [cherry-pick] Limit milvus-lite files to end with .db
  pymilvus/orm/connections.py
  tests/test_milvus_lite.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2212 enhance: use info level for retry message
  pymilvus/decorators.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2214 Limit milvus-lite files to end with .db
  pymilvus/orm/connections.py
  tests/test_milvus_lite.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2210 fix: select a single column consisting of a list of column names
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2223 Bulkinsert supports importing binlog
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2224 enhance: upsert support autoid (#2173)
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/exceptions.py
  pymilvus/orm/collection.py
  pymilvus/orm/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2222 Bulkinsert supports importing binlog
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2230 feat: [2.4] add page_retain_order param during search with offset
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  tests/test_prepare.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2229 feat: add page_retain_order param during search with offset
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
  tests/test_prepare.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2219 Rename is_major to is_clustering
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/stub.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2234 enhance: support null and default value
  pymilvus/bulk_writer/buffer.py
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/orm/iterator.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2238 feat: support the mmap_enable param in the field schema
  pymilvus/client/abstract.py
  pymilvus/client/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2239 feat: [2.4] support the mmap_enable param in the field schema
  pymilvus/bulk_writer/buffer.py
  pymilvus/client/abstract.py
  pymilvus/client/prepare.py
  pymilvus/orm/iterator.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2240 enhance: [cp24] loose grpcio upper limit
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2241 enhance: loose the upper limit for grpcio
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2243 enhance: Make load parameter naming normal
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2244 enhance: [2.4] Make load parameter naming normal (#2243)
  pymilvus/client/grpc_handler.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed
