Repository milvus-io/pymilvus, pull requests merged in 2024-06, with the labels that each got.

#2114 fix: wrong expr handling due to and/or priorities(#2113)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, needs-dco

#2111 Accept list of single row scipy.sparse object as input for insert/search
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/S, ci-passed, needs-dco

#2112 [2.4] Accept list of single row scipy.sparse object as input for insert/search
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/S, ci-passed, needs-dco

#2107 fix: use the existed index_name
  pymilvus/orm/index.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2115 fix wrong expr handling due to and/or priorities(#2113)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, needs-dco

#2118 fix: use the existed index_name (#2107)
  pymilvus/orm/index.py
Labels: approved, lgtm, size/XS, ci-passed, needs-dco

#2124 enhance: print search result more elegantly (#2123)
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2123 enhance: print search result more elegantly
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2121 change the load status check interval to 0.2s
  pymilvus/settings.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2125 [2.4] change the load status check interval to 0.2s
  pymilvus/settings.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2127 Support float16/bfloat16/sparse vector for bulkwriter
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/validators.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2128 Support float16/bfloat16/sparse vector for bulkwriter
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/validators.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2132 Fix a bug of bulkwriter
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/validators.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2133 Fix a bug of bulkwriter
  examples/example_bulkwriter.py
  pymilvus/bulk_writer/validators.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2134 feat: disable installation of milvus-lite on windows platform (#2131)
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2136 enhance: Check PyMilvus on Windows platform
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/pull_request.yml
  Makefile
  tests/test_milvus_lite.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2137 feat: Disable installation of milvus-lite on windows platform
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/pull_request.yml
  Makefile
  pyproject.toml
  tests/test_milvus_lite.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2138 fix: drop_index got multiple values for keyword argument
  pymilvus/orm/collection.py
  pymilvus/orm/index.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2142 enhance: update milvus-proto and correct index.drop()
  .github/mergify.yml
  pymilvus/orm/index.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2146 enhance: Update readme to the latest
  README.md
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2130 feat: support group_size parameter for search_group_by
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2148 Export indexed rows for describe_index
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2149 Export indexed rows for describe_index (#2148)
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2156 Refine the error message for type mismatches during data insertion
  pymilvus/client/entity_helper.py
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2157 Refine the error message for type mismatches during data insertion (#2156)
  pymilvus/client/entity_helper.py
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed
