Repository milvus-io/pymilvus, pull requests merged in 2024-12, with the labels that each got.

#2387 fix: type annotation in Hits and docs in Collection
  pymilvus/client/abstract.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2388 enhance: update float16/bfloat16 examples
  examples/datatypes/bfloat16_example.py
  examples/datatypes/float16_example.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2397 fix: Unify logger and correct logging settings
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_import.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/settings.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2399 fix: fix list aliases rpc call
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2403 fix: remove grant/revoke v2 optional collection name
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/role.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2404 fix: [2.4] fix list aliases rpc call and grant/revoke v2
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/role.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2405 fix: [2.5] fix list aliases rpc call and grant/revoke v2
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/role.py
  pymilvus/orm/utility.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2420 extend unlimted offset for query iterator(#2418)
  examples/orm/iterator.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2419 extend unlimted offset for query iterator(#2418)
  examples/orm/iterator.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2421 extend unlimted offset for query iterator(#2418)
  examples/orm/iterator.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2425 enhance: rbac privilege group and grant v2 examples
  examples/orm/rbac.py
  examples/rbac.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2428 fix: Add is_clustering params for get_compaction_plans in orm
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2429 fix: [2.4]Add is_clustering params for get_compaction_plans in orm
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2430 fix: [2.5]Add is_clustering params for get_compaction_plans in orm
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2426 enhance: [2.4] rbac privilege group and grant v2 examples
  examples/orm/rbac.py
  examples/rbac.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2427 enhance: [2.5] rbac privilege group and grant v2 examples
  examples/orm/rbac.py
  examples/rbac.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2433 enhance: add describe and alter database in MilvusClient
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2438 fix pkg_resources api deprecated warning
  pymilvus/client/__init__.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2401 fix: [25]Unify logger and correct logging settings (#2397)
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_import.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/settings.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2413 enhance: refine query iterator cp(#2412)
  examples/orm/iterator.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2441 enhance: refine query iterator cp(#2412)
  examples/orm/iterator.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2408 enhance: support hints param
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2402 fix: [24]Unify logger and correct logging settings (#2397)
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_import.py
  pymilvus/bulk_writer/local_bulk_writer.py
  pymilvus/bulk_writer/remote_bulk_writer.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/settings.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2443 enhance: Add example for milvus client about expression template
  examples/search_with_template_expression.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2444 enhance: [2.5]Add example for milvus client about expression template
  examples/search_with_template_expression.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2445 enhance: [2.4]Add example for milvus client about expression template
  examples/search_with_template_expression.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2448 enhance: createdatabase support properties
  pymilvus/client/grpc_handler.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2450 enhance: [2.4]createdatabase support properties
  pymilvus/client/grpc_handler.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2449 enhance: [2.5] createdatabase support properties
  pymilvus/client/grpc_handler.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2451 fix: fix describe database return type
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2452 fix: [2.5]fix describe database return type
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2453 fix: [2.4]fix describe database return type
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2458 feat: [2.5] asyncio support
  examples/simple_async.py
  pymilvus/__init__.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/async_interceptor.py
  pymilvus/milvus_client/__init__.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#2459 feat: [2.4] asyncio support
  examples/simple_async.py
  pymilvus/__init__.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/async_interceptor.py
  pymilvus/milvus_client/__init__.py
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#2462 fix: [2.4] resolve conflicts and update connections.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2466 feature: support milvus-client iterator(#2465)
  examples/iterator/iterator.py
  pymilvus/client/utils.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/constants.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2465 feature: support milvus-client iterator
  examples/iterator/iterator.py
  pymilvus/client/utils.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/constants.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2461 enhance: support milvus-client iterator
  examples/iterator/iterator.py
  pymilvus/client/utils.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/constants.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2467 fix: add `authorization_interceptor` and `db_interceptor` to async channel
  examples/simple_async.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/async_interceptor.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2471 fix: call wrong function name when creating collection without schema
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2473 fix: [2.5] add `authorization_interceptor` and `db_interceptor` to async channel
  examples/simple_async.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/async_interceptor.py
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2476 fix: ensure `create_index` and `load_collection` are fully completed
  pymilvus/client/async_grpc_handler.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2482 enhance: add search_group_by example for milvus-client(#2481)
  examples/search_group_by.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2483 enhance: add search_group_by example for milvus-client(#2481)
  examples/search_group_by.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2484 enhance: add search_group_by example for milvus-client(#2481)
  examples/search_group_by.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2485 enhance: refine search_group_by_example(#2481)
  examples/search_group_by.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2486 enhance: [2.5]add example for null and default_value
  examples/orm/nullable_and_default_value.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2487 fix: remove async function in AsyncClient connection initialization
  pymilvus/client/async_grpc_handler.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2478 fix: [2.5] ensure `create_index` and `load_collection` are fully completed
  pymilvus/client/async_grpc_handler.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2477 fix: [2.4] ensure `create_index` and `load_collection` are fully completed
  pymilvus/client/async_grpc_handler.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2489 fix: [2.5]Support hybrid search with expression template
  examples/hybrid_search.py
  examples/hybrid_search/hybrid_search.py
  pymilvus/client/abstract.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2479 enhance: add example for null and default_value
  examples/orm/nullable_and_default_value.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2490 fix: [2.4] Support hybrid search with expression template
  examples/hybrid_search.py
  examples/hybrid_search/hybrid_search.py
  pymilvus/client/abstract.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2488 fix: Support hybrid search with expression template
  examples/hybrid_search.py
  examples/hybrid_search/hybrid_search.py
  pymilvus/client/abstract.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2492 enhance: add use_database
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2493 enhance: add use_database
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2491 enhance: add use_database
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2497 fix: RuntimeWarning: coroutine 'Channel.close' was never awaited when closing async client
  pymilvus/client/async_grpc_handler.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2498 fix: [2.4] RuntimeWarning: coroutine 'Channel.close' was never awaited when closing async client
  pymilvus/client/async_grpc_handler.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2499 fix: [2.5] RuntimeWarning: coroutine 'Channel.close' was never awaited when closing async client
  pymilvus/client/async_grpc_handler.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2500 fix: await conn.describe_collection in async client's query
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2501 fix: [2.4] await conn.describe_collection in async client's query
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2502 fix: [2.5] await conn.describe_collection in async client's query
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2417 fix: Fix sparse slice bug in hello_model.py(#2414)
  examples/milvus_model/hello_model.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2504 enhance: add alter properties example
  examples/alter.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2505 enhance: [2.5]add alter properties example
  examples/alter.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2506 enhance: [2.4]add alter properties example
  examples/alter.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2508 fix: grant ManualCompact api doesn't work (#2396)
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2509 fix: grant ManualCompact api doesn't work (#2396)
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2510 fix: fix privilege typo
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2511 fix: [2.4] fix privilege typo
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2512 fix: [2.5] fix privilege typo
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2513 enhance: Enable resource group api in milvus client
  examples/resource_group.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2514 enhance: Enable resource group api in milvus client (#2513)
  examples/resource_group.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2515 enhance: Enable resource group api in milvus client (#2513)
  examples/resource_group.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2516 enhance: add database operation example
  examples/database.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2517 enhance: [2.5]add database operation example
  examples/database.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2518 enhance: [2.4]add database operation example
  examples/database.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2520 fix: indentations in docs .rst tables
  docs/source/api/collection.rst
  docs/source/api/partition.rst
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2446 Add `db_name` parameter at `bulk_import`
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2395 enhance: add search iterator v2
  pymilvus/client/abstract.py
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
  pymilvus/client/search_iterator.py
  pymilvus/exceptions.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2524 enhance: [2.5][cp] add search iterator v2
  pymilvus/client/abstract.py
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
  pymilvus/client/search_iterator.py
  pymilvus/exceptions.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2526 enhance:refine search iter v2 warning
  pymilvus/exceptions.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2527 enhance:refine search iter v2 warning
  pymilvus/exceptions.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2525 enhance: add release_collection, drop_index, create_partition, drop_partition, load_partition and release_partition
  pymilvus/client/async_grpc_handler.py
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2528 enhance: [2.4] add release_collection, drop_index, create_partition, drop_partition, load_partition and release_partition
  pymilvus/client/async_grpc_handler.py
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2529 enhance: [2.5] add release_collection, drop_index, create_partition, drop_partition, load_partition and release_partition
  pymilvus/client/async_grpc_handler.py
  pymilvus/milvus_client/async_milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2532 fix: [2.5] fix search iter v2 limit compatibility
  pymilvus/client/search_iterator.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2531 fix: fix search iter v2 limit compatibility
  pymilvus/client/search_iterator.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2534 enhance: [2.4] add example code for create_collection, drop_collection, load_collection, release_collection, create_index, drop_index, create_partition, drop_partition, load_partition and release_partition
  examples/simple_async2.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2533 enhance: add example code for create_collection, drop_collection, load_collection, release_collection, create_index, drop_index, create_partition, drop_partition, load_partition and release_partition
  examples/simple_async2.py
  pymilvus/client/async_grpc_handler.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2535 enhance: [2.5] add example code for create_collection, drop_collection, load_collection, release_collection, create_index, drop_index, create_partition, drop_partition, load_partition and release_partition
  examples/simple_async2.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2507 enhance: simplify the structure of search_params
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed
