Repository milvus-io/pymilvus, pull requests merged in 2025-01, with the labels that each got.

#2537 fix: get get param from wrong dict
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2540 fix: check params consistency failed in search iterator v1
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2544 Remove long deprecated Milvus class
  pymilvus/__init__.py
  pymilvus/client/stub.py
  tests/test_create_collection.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#2547 enhance: Publishing with trusted publisher
  .github/workflows/publish_dev_package.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2550 enhance: simplify the structure of search_params(#2507)(#2537)(#2540)
  pymilvus/client/prepare.py
  pymilvus/client/utils.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2548 enhance: use trusted publisher and remove deprecated
  .github/workflows/publish_dev_package.yml
  pymilvus/__init__.py
  pymilvus/client/stub.py
  tests/test_create_collection.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#2549 enhance: use trusted publisher and remove deprecated
  .github/workflows/publish_dev_package.yml
  pymilvus/__init__.py
  pymilvus/client/stub.py
  tests/test_create_collection.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#2552 enhance: support recalls for milvus_client
  pymilvus/client/abstract.py
  pymilvus/client/types.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/milvus_client.py
  pyproject.toml
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2553 enhance: [2.5] support recalls for milvus_client
  pymilvus/client/abstract.py
  pymilvus/client/types.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/milvus_client.py
  pyproject.toml
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2570 fix: [2.5] use dummy call for search iterator v2 compatibility
  pymilvus/client/search_iterator.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2569 fix: use dummy call for search iterator v2 compatibility
  pymilvus/client/search_iterator.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2568 fix: iterator mismatch when alter alias and database(#2555)
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
  pymilvus/orm/constants.py
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2564 fix typo(#2563)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2563 fix typo
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2574 fix: unset collection_name for search iterator_v1(#2555)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2578 fix: [2.5] should not modify users search_param, copy instead
  pymilvus/client/utils.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2577 fix: should not modify users search_param, copy instead
  pymilvus/client/utils.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2580 enhance: Publishing releases with trusted publisher
  .github/workflows/publish_on_release.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2581 enhance: [25]Publishing releases with trusted publisher
  .github/workflows/publish_on_release.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2582 enhance: [24]Publishing releases with trusted publisher
  .github/workflows/publish_on_release.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2583 fix: Cannot publish to too destinations in one action
  .github/workflows/publish_on_release.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2584 fix: Cannot publish to too destinations in one action
  .github/workflows/publish_on_release.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2585 fix: Cannot publish to too destinations in one action
  .github/workflows/publish_on_release.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2595 enhance: Use new model pkg
  pymilvus/model/__init__.py
  pyproject.toml
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2541 enhance: enable describe_replica api in milvus client
  examples/partition.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2598 enhance: Add schema update time verification to insert and upsert to use cache
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2599 enhance: enable describe_replica api in milvus client (#2541)
  examples/partition.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed
