Repository milvus-io/pymilvus, pull requests merged in 2025-02, with the labels that each got.

#2608 enhance: [2.4]get and delete to use schema cache
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2606 enhance: get and delete to use schema cache
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2607 enhance: [2.5]get and delete to use schema cache
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2614 fix: Use ubuntu22.04 instead of latest
  .github/mergify.yml
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/doc_update_event.yml
  .github/workflows/nightly_ci.yml
  .github/workflows/pull_request.yml
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2611 enhance: support Int8Vector
  examples/datatypes/int8_example.py
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/types.py
  pymilvus/orm/schema.py
  tests/test_abstract.py
  tests/test_collection.py
  tests/test_schema.py
  tests/test_types.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2615 fix: Use ubuntu22.04 instead of latest
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/nightly_ci.yml
  .github/workflows/pull_request.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2616 fix: [24]Use ubuntu22.04 instead of latest
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/doc_update_event.yml
  .github/workflows/pull_request.yml
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2623 Fix BulkWriter bug for Array type field
  examples/bulk_import/example_bulkwriter.py
  pymilvus/bulk_writer/constants.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2624 Fix BulkWriter bug for Array type field
  examples/bulk_import/example_bulkwriter.py
  pymilvus/bulk_writer/constants.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2625 Fix BulkWriter bug for Array type field
  examples/bulk_import/example_bulkwriter.py
  pymilvus/bulk_writer/constants.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2627 fix: remove set batchsize to ef for param flat(#2626)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2629 fix: fix int8_example.py
  examples/datatypes/int8_example.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2631 fix: fix query int8_vector
  pymilvus/client/utils.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2632 Support bulk insert for INT8_VECTOR
  examples/bulk_import/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/validators.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/entity_helper.py
  pymilvus/client/utils.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2635 fix: Unify output of str(DataType) for different pythons
  pymilvus/client/types.py
  tests/test_types.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2636 Fix BulkWriter bug for nullable field
  examples/bulk_import/example_bulkwriter_with_nullable.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/bulk_writer.py
  pymilvus/bulk_writer/constants.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2618 enhance: describecollection output add created_timestamp
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2639 feat: add external filter func for search iterator v2
  examples/iterator/iterator.py
  pymilvus/client/search_iterator.py
  tests/test_search_iterator.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2637 fix: Unify output of str(DataType) for different pythons (#2635)
  pymilvus/client/types.py
  tests/test_types.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2638 fix: Unify output of str(DataType) for different pythons (#2635)
  pymilvus/client/types.py
  tests/test_types.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2647 grpc thread is not released each time connections.connect() is failed
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2649 grpc thread is not released each time connections.connect() is failed
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2620 enhance: [2.4]describecollection output add created_timestamp
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2590 fix: update properties parameter type in alter_collection_properties …
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2655 Fix bug for BulkWriter with nullable/default_value fields
  examples/bulk_import/example_bulkwriter_with_nullable.py
  pymilvus/bulk_writer/bulk_writer.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2653 Fix bug for BulkWriter with nullable/default_value fields
  examples/bulk_import/example_bulkwriter_with_nullable.py
  pymilvus/bulk_writer/bulk_writer.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2657 fix: correct Int8Vector handle wrong insert data type
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2652 feat: Text embedding supports int8 vector
  pymilvus/exceptions.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2669 fix: remove set batchsize to ef for param flat(#2626)
  pymilvus/orm/iterator.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2673 fix [2.4]: Allow empty sparse
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed
