Repository milvus-io/pymilvus, pull requests merged in 2025-06, with the labels that each got.

#2836 feat: support load collection/partition with priority(#2835)
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2834 fix: [cp25]remove calling of deregister_state_change_callback
  pymilvus/client/async_grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2845 enahnce:[2.5] dump analyzer params when init field schema
  pymilvus/client/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2844 enhance: dump analyzer params when init field schema
  pymilvus/client/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2849 enhance: optimize perf for large topk(#2848)
  pymilvus/client/entity_helper.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2853 fix: Bypass FD shutdown by downgrading grpc to <1.68.0
  pyproject.toml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2856 fix: remove validation for collection_id in manual_compaction method
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2857 fix: remove validation for collection_id in manual_compaction method
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2861 enhance: [25]fix according to the latest ruff
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/check.py
  pymilvus/client/utils.py
  pymilvus/orm/connections.py
  pymilvus/orm/index.py
  pymilvus/orm/partition.py
  pymilvus/orm/utility.py
  pyproject.toml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2862 fix: hybridExtraList miss iter method
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/search_result.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2866 fix: hybridExtraList miss iter method and dynamic fields value overrite fixed field value(#2848)
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/search_result.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2870 enhance: make query result mutable for only one time modification
  pymilvus/client/search_result.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2873 enhance: reuse channel by default
  .gitignore
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2880 Revert "Enhance MilvusClient Initialization and Connection Management…
  examples/loop_create_milvus_client.py
  examples/with_usage.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed
