Repository milvus-io/pymilvus, pull requests merged in 2025-03, with the labels that each got.

#2666 Add `db_name` parameter at `bulk_import` (#2446)
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2667 enhance: [25]add examples for text match (#2383)
  examples/orm/hello_text_match.py
  examples/text_match.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2665 fix: [cp25]Add and check timeout param in database api
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2668 enhance: Multi-cp from master to 2.5.x
  examples/datatypes/bfloat16_example.py
  examples/datatypes/float16_example.py
  examples/milvus_model/hello_model.py
  pymilvus/client/__init__.py
  pymilvus/client/abstract.py
  pymilvus/model/__init__.py
  pymilvus/orm/collection.py
  pyproject.toml
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2678 Fix 2670: db_name overwritten by empty string
  pymilvus/orm/connections.py
  tests/test_connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2686 fix: Fix failure of create multiple indices for a field
  pymilvus/milvus_client/index.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2685 fix: Remove field check in create_index (#2677)
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2687 fix: Fix failure of create multiple indices for a field
  pymilvus/milvus_client/index.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2684 enhance: Support Python3.13 and upgrade grpcio range
  .github/mergify.yml
  .github/workflows/check_milvus_proto.yml
  .github/workflows/code_checker.yml
  .github/workflows/publish_dev_package.yml
  .github/workflows/publish_on_release.yml
  pymilvus/grpc_gen/common_pb2.py
  pymilvus/grpc_gen/feder_pb2.py
  pymilvus/grpc_gen/milvus_pb2.py
  pymilvus/grpc_gen/milvus_pb2_grpc.py
  pymilvus/grpc_gen/msg_pb2.py
  pymilvus/grpc_gen/rg_pb2.py
  pymilvus/grpc_gen/schema_pb2.py
  pyproject.toml
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#2690 enhance: Convert json_cast_type to DataType
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2692 Revert "enhance: Convert json_cast_type to DataType (#2690)"
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2694 enhance: Update mergify check more generally
  .github/mergify.yml
  .github/workflows/pull_request.yml
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2700 fix: Remove not useful SequenceIterator
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2702 fix: [cp25]db_name overwritten by empty string (#2678)
  pymilvus/orm/connections.py
  tests/test_connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2705 enhance: Add force_drop parameter to drop_role method for role deletion
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2706 enhance: [2.5] Add force_drop parameter to drop_role method for role deletion
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2704 enhance: add property func for AnalyzeToken
  pymilvus/client/types.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2708 weighted reranker to allow skip score normalization
  examples/hybrid_search.py
  examples/hybrid_search/hybrid_search.py
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2709 [2.5] weighted reranker to allow skip score normalization
  examples/hybrid_search.py
  examples/hybrid_search/hybrid_search.py
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed
