Repository milvus-io/pymilvus, pull requests merged in 2025-08, with the labels that each got.

#2907 enhance: Add usage guide to manage MilvusClient
  examples/manage_milvus_client/how_to_manage_milvus_client.md
  examples/manage_milvus_client/manage_milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2929 Avoid describe_collection when query by ids
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2933 [cherry-pick] bulkImport add objectUrls/token paramster & add example use
  examples/bulk_import/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2932 bulkImport add objectUrls/token paramster & add example use
  examples/bulk_import/example_bulkwriter.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2937 enhance: Tidy ut code in pytest
  pymilvus/client/grpc_handler.py
  pyproject.toml
  tests/conftest.py
  tests/pytest.ini
  tests/ruff.toml
  tests/test_bulk_writer_buffer.py
  tests/test_bulk_writer_buffer_extended.py
  tests/test_bulk_writer_stage.py
  tests/test_bulk_writer_validators.py
  tests/test_check.py
  tests/test_client_entity_helper.py
  tests/test_client_entity_helper_extended.py
  tests/test_collection.py
  tests/test_connections.py
  tests/test_decorators.py
  tests/test_grpc_handler.py
  tests/test_grpc_handler_mutations.py
  tests/test_milvus_client.py
  tests/test_milvus_lite.py
  tests/test_schema.py
  tests/test_search_iterator.py
  tests/test_types.py
  tests/utils.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2941 enhance: Add automatic pr actions every night
  .github/workflows/update-milvus-pymilvus-dev.yml
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2944 fix: Install setuptools_scm in python module
  .github/workflows/update-milvus-pymilvus-dev.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2946 fix: Use the correct github token in remote
  .github/workflows/update-milvus-pymilvus-dev.yml
  _version_helper.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2948 fix: Force to use author rather thant github-bot
  .github/workflows/update-milvus-pymilvus-dev.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2949 fix: Correct token usage
  .github/workflows/update-milvus-pymilvus-dev.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2950 fix: invalid yml file
  .github/workflows/update-milvus-pymilvus-dev.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2952 enhance: Remove requirements.txt
  pyproject.toml
  requirements.txt
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2953 fix: Remove tmate and clear credentials in checkout
  .github/workflows/update-milvus-pymilvus-dev.yml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2956 enhance: Make pr to fix the empty head error
  .github/workflows/update-milvus-pymilvus-dev.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2957 enhance: Add unixmsec in every RPC call
  .pre-commit-config.yaml
  Makefile
  README.md
  pymilvus/client/interceptor.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2963 fix: Passing unknown req.is_refresh to wait
  pymilvus/client/async_grpc_handler.py
  pyproject.toml
  tests/test_async_grpc_handler.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2965 fix: [2.5]Passing unknown req.is_refresh to wait
  pymilvus/client/async_grpc_handler.py
  pyproject.toml
  tests/test_async_grpc_handler.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed
