Repository milvus-io/pymilvus, pull requests merged in 2025-09, with the labels that each got.

#2967 enhance: Run actions when push to repo to enable cov compare
  .github/workflows/pull_request.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2970 fix: Refine partial upsert to preserve unspecified fields (#2955)
  pymilvus/client/prepare.py
  pymilvus/exceptions.py
  tests/test_prepare.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2974 fix: Correct validation logic for partial upsert requests
  pymilvus/client/prepare.py
  tests/test_prepare.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2972 enhance: Move all orm styled examples into orm_deprecated/
  examples/bulk_import/example_bulkwriter_stage.py
  examples/bulk_import/test.py
  examples/datatypes/int8_example.py
  examples/int8_example.py
  examples/iterator/iterator.py
  examples/orm_deprecated/bitmap_index_example.py
  examples/orm_deprecated/bulk_import/data_gengerator.py
  examples/orm_deprecated/bulk_import/example_bulkinsert_csv.py
  examples/orm_deprecated/bulk_import/example_bulkinsert_json.py
  examples/orm_deprecated/bulk_import/example_bulkinsert_numpy.py
  examples/orm_deprecated/bulk_import/example_bulkinsert_withfunction.py
  examples/orm_deprecated/bulk_import/example_bulkwriter.py
  examples/orm_deprecated/bulk_import/example_bulkwriter_with_nullable.py
  examples/orm_deprecated/bulk_import/train_embeddings.csv
  examples/orm_deprecated/collection.py
  examples/orm_deprecated/concurrency/multithreading_hello_milvus.py
  examples/orm_deprecated/database.py
  examples/orm_deprecated/datatypes/bfloat16_example.py
  examples/orm_deprecated/datatypes/binary_example.py
  examples/orm_deprecated/datatypes/dynamic_field.py
  examples/orm_deprecated/datatypes/example_str.py
  examples/orm_deprecated/datatypes/float16_example.py
  examples/orm_deprecated/datatypes/fuzzy_match.py
  examples/orm_deprecated/datatypes/hello_bm25.py
  examples/orm_deprecated/datatypes/hello_milvus_array.py
  examples/orm_deprecated/datatypes/hello_sparse.py
  examples/orm_deprecated/example.py
  examples/orm_deprecated/example_group_by.py
  examples/orm_deprecated/example_index.py
  examples/orm_deprecated/gpu_indx/example_gpu_brute_force.py
  examples/orm_deprecated/gpu_indx/example_gpu_cagra.py
  examples/orm_deprecated/hello_cost.py
  examples/orm_deprecated/hello_milvus.ipynb
  examples/orm_deprecated/hello_milvus.py
  examples/orm_deprecated/hello_milvus_delete.py
  examples/orm_deprecated/hello_text_embedding.py
  examples/orm_deprecated/hello_text_match.py
  examples/orm_deprecated/hybrid_search/hello_hybrid_bm25.py
  examples/orm_deprecated/hybrid_search/hello_hybrid_sparse_dense.py
  examples/orm_deprecated/hybrid_search/hybrid_search.py
  examples/orm_deprecated/inverted_index_example.py
  examples/orm_deprecated/iterator.py
  examples/orm_deprecated/nullable_and_default_value.py
  examples/orm_deprecated/partition.py
  examples/orm_deprecated/rbac.py
  examples/orm_deprecated/resource_group.py
  examples/orm_deprecated/resource_group_declarative_api.py
  examples/orm_deprecated/role_and_privilege.py
  examples/orm_deprecated/search_with_template_expression.py
  examples/orm_deprecated/user.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#2979 feat: support group by json field(#2884)
  pymilvus/client/constants.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2969 enhance: [2.6]Run actions when push to repo to enable cov compare
  .github/workflows/pull_request.yml
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2976 enhance: Make milvus-lite an optional dependency
  pymilvus/orm/connections.py
  pyproject.toml
  tests/test_milvus_lite.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2987 support connectType if use oss-bucket
  examples/bulk_import/example_stage_file_manager.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/endpoint_resolver.py
  pymilvus/bulk_writer/stage_bulk_writer.py
  pymilvus/bulk_writer/stage_file_manager.py
  tests/test_bulk_writer_stage.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2989 [cherry-pick] support connectType if use oss-bucket
  examples/bulk_import/example_stage_file_manager.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/endpoint_resolver.py
  pymilvus/bulk_writer/stage_bulk_writer.py
  pymilvus/bulk_writer/stage_file_manager.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2988 [cherry-pick] support connectType if use oss-bucket
  examples/bulk_import/example_stage_file_manager.py
  pymilvus/bulk_writer/constants.py
  pymilvus/bulk_writer/endpoint_resolver.py
  pymilvus/bulk_writer/stage_bulk_writer.py
  pymilvus/bulk_writer/stage_file_manager.py
  tests/test_bulk_writer_stage.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#3000 enhance: [2.6] update get_cost_from_status
  pymilvus/client/types.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2993 enhance: Replace ujson with orjson
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
  pymilvus/client/prepare.py
  pymilvus/client/search_result.py
  pymilvus/client/types.py
  pymilvus/client/utils.py
  pymilvus/orm/partition.py
  pymilvus/orm/schema.py
  pyproject.toml
  tests/test_search_result.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#3010 feat: [2.6] support use function scorer as ranker not one function
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2992 feat: support use function scorer as ranker not one function
  pymilvus/__init__.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x
