Repository milvus-io/pymilvus, pull requests merged in 2025-07, with the labels that each got.

#2882 enhance: Cherry pick multiple prs
  .gitignore
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/connections.py
  requirements.txt
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2883 fix: bulkwriter int8_vector issue
  examples/bulk_import/example_bulkwriter.py
  pymilvus/bulk_writer/buffer.py
  pymilvus/bulk_writer/validators.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2889 enhance: add error log when json load fails
  pymilvus/client/abstract.py
  pymilvus/client/entity_helper.py
  pymilvus/client/search_result.py
  pymilvus/client/types.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2890 fix: Fix hybrid search params check
  pymilvus/client/async_grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2887 fix: refine error message
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2892 fix: different token should not reuse connection
  pymilvus/milvus_client/milvus_client.py
  tests/test_milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2878 [fix]: Fix compaction params error in async grpc handler & [Add]: Previledge async test & resource group test
  examples/async_DDL_test.py
  examples/async_previledge_test.py
  pymilvus/client/async_grpc_handler.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2894 enhance: Store alias before wait for ready
  pymilvus/milvus_client/_utils.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/connections.py
  tests/test_milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2893 support stage operation
  examples/stage/example_stage.py
  pymilvus/client/abstract.py
  pymilvus/client/asynch.py
  pymilvus/client/search_result.py
  pymilvus/settings.py
  pymilvus/stage/__init__.py
  pymilvus/stage/file_utils.py
  pymilvus/stage/stage_operation.py
  pymilvus/stage/stage_restful.py
  pyproject.toml
  tests/test_file_utils.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2895 [cherry-pick] support stage
  examples/stage/example_stage.py
  pymilvus/client/asynch.py
  pymilvus/client/search_result.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/settings.py
  pymilvus/stage/__init__.py
  pymilvus/stage/file_utils.py
  pymilvus/stage/stage_operation.py
  pymilvus/stage/stage_restful.py
  pyproject.toml
  tests/test_file_utils.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2904 bulk_import add stageName/dataPaths parameter
  examples/bulk_import/test.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2905 [cherry-pick] bulk_import add stageName/dataPaths parameter
  examples/bulk_import/test.py
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2913 [cherry-pick] Compatible with the default behavior of free on the cloud
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2914 fix: Return new pk value for upsert when autoid=true
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2915 fix: Return new pk value for upsert when autoid=true
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2919 add example code for language identifier and multi analyzer
  examples/full_text_search/bm25.py
  examples/full_text_search/language_identifier.py
  examples/full_text_search/multi_analyzer.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed
