Repository milvus-io/pymilvus, pull requests merged in 2025-04, with the labels that each got.

#2713 fix: Retry batch insert will use changed entites if enabled Nullable
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2714 fix: [cp25]Retry batch insert will use changed entites if enabled Nul…
  pymilvus/client/entity_helper.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2720 Add options parameter for bulk_import interface
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2721 Add options parameter for bulk_import interface
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2718 fix: Raise ParamError if index params wrong
  examples/simple_async.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/check.py
  pymilvus/milvus_client/index.py
  pymilvus/milvus_client/milvus_client.py
  tests/conftest.py
  tests/test_milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2719 fix: Raise ParamError if index params wrong
  examples/simple_async.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/check.py
  pymilvus/milvus_client/index.py
  pymilvus/milvus_client/milvus_client.py
  tests/conftest.py
  tests/test_milvus_client.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2725 doc: add time unit for constructor
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2672 Add Optional CA Certificate Support to Bulk Import Functions
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2726 enhance: Update pyproject toml and readme
  README.md
  pyproject.toml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2730 enhance: Use hyphen instead of underscore in grpc header
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2731 enhance: [2.5] Use hyphen instead of underscore in grpc header (#2730)
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/grpc_handler.py
  pymilvus/decorators.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2734 fix: db_name will be overwritten by mistake
  pymilvus/orm/connections.py
  tests/test_connections.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2735 enhance: Use SearchResult in MilvusClient
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/search_iterator.py
  pymilvus/client/search_reasult.py
  pymilvus/client/types.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
  pymilvus/orm/future.py
  pymilvus/orm/iterator.py
  pymilvus/orm/partition.py
  pyproject.toml
  tests/test_search_iterator.py
  tests/test_search_result.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#2737 fix: [2.5]Remove deprecated numpy.bool8
  pymilvus/orm/types.py
  pyproject.toml
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2729 Support rerank
  examples/simple_rerank.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/client/types.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2741 fix: None return for validate
  pymilvus/client/search_reasult.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/check.py
  pymilvus/milvus_client/index.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/types.py
  tests/test_milvus_client.py
  tests/test_search_result.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2740 enhance: [25]Use SearchResult in MilvusClient (#2735)
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/search_iterator.py
  pymilvus/client/search_reasult.py
  pymilvus/client/types.py
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/collection.py
  pymilvus/orm/future.py
  pymilvus/orm/iterator.py
  pymilvus/orm/partition.py
  tests/test_search_iterator.py
  tests/test_search_result.py
Labels: approved, lgtm, size/XXL, ci-passed, dco-passed

#2744 fix: Remove the class params of search result
  pymilvus/client/search_reasult.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2728 Add example code for privilege group crud
  examples/privilege_group.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2739 Add Optional CA Certificate Support to Bulk Import Functions (#2672)
  pymilvus/bulk_writer/bulk_import.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2745 fix: Omit empty index types
  pymilvus/client/prepare.py
  pymilvus/milvus_client/index.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2746 fix: Omit empty index types
  pymilvus/client/prepare.py
  pymilvus/milvus_client/index.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2747 feat: suppoprt multi analyzer params
  pymilvus/client/prepare.py
  pymilvus/orm/constants.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2751 feat:[2.5] suppoprt multi analyzer params (#2747)
  pymilvus/client/prepare.py
  pymilvus/orm/constants.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2760 Add funciton checker
  pymilvus/client/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2762 Fix hybrid search params check
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2752 fix: Correct module misspell and patch for submodule
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/search_iterator.py
  pymilvus/client/search_result.py
  pymilvus/orm/collection.py
  pymilvus/orm/future.py
  pymilvus/orm/iterator.py
  pymilvus/orm/partition.py
  tests/test_check.py
  tests/test_search_iterator.py
  tests/test_search_result.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2753 fix: Correct module misspell and patch for submodule
  pymilvus/__init__.py
  pymilvus/client/abstract.py
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/asynch.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/search_iterator.py
  pymilvus/client/search_result.py
  pymilvus/orm/collection.py
  pymilvus/orm/future.py
  pymilvus/orm/iterator.py
  pymilvus/orm/partition.py
  tests/test_check.py
  tests/test_search_iterator.py
  tests/test_search_result.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2768 fix: [AddField] Fill default value in `get_field_schema`
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2770 Fix function construct bug
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed
