Repository milvus-io/pymilvus, pull requests merged in 2025-05, with the labels that each got.

#2766 fix: Pass request-id in metadata per API
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/interceptor.py
  pymilvus/decorators.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed, PR | need to cherry-pick to 2.x

#2777 fix: Handle collection schema update timestamp
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2779 fix: [cp25]Pass request-id in metadata per API (#2766)
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/interceptor.py
  pymilvus/decorators.py
Labels: approved, lgtm, ci-passed, size/XL, dco-passed

#2782 fix: remove default replica_number in load_collection
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2778 fix: [2.5] Handle collection schema update timestamp (#2777)
  pymilvus/client/abstract.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2786 fix: [cp25]remove default replica_number in load_collection (#2782)
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
  pymilvus/orm/collection.py
  pymilvus/orm/partition.py
Labels: approved, lgtm, size/L, ci-passed, dco-passed

#2787 fix: Extend iterable instead of assign load_fields
  pymilvus/client/prepare.py
  tests/test_prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2788 fix: [25]Extend iterable instead of assign load_fields
  pymilvus/client/prepare.py
  tests/test_prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2793 fix: Update schema and retry when data not match
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2792 fix: [cp25]Missing kwargs in load_partition
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2791 fix: Missing kwargs in load_partition
  pymilvus/client/grpc_handler.py
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2801 fix: [cp25]load collection with resource group
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2795 Function params support complex data
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2800 fix: load collection with resource group
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2805 enhance: [AddField] Use functional signature for add_collection_field
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed

#2799 fix: [cp25]avoid collision on aliases in MilvusClient (#2716)
  pymilvus/milvus_client/milvus_client.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2783 enhance: Set keep_alive check by default
  pymilvus/client/async_grpc_handler.py
  pymilvus/orm/connections.py
  tests/test_collection.py
  tests/test_connections.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2806 Fixes hasattr checks against Hit for missing attributes
  pymilvus/client/search_result.py
  tests/test_search_result.py
Labels: approved, lgtm, size/S, ci-passed, dco-passed, PR | need to cherry-pick to 2.x

#2809 fix: Pass element type param when converting field schema
  pymilvus/client/prepare.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2790 fix: wrong marshal field schema prarams case alter collection failed
  pymilvus/client/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2811 fix:[2.5] wrong marshal field schema prarams case alter collection failed
  pymilvus/client/prepare.py
  pymilvus/orm/schema.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2819 fix: [2.5] Pass correct number of params of _prepare_row_upsert_request
  pymilvus/client/grpc_handler.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed

#2816 fix: MilvusClient misusage of disconnect
  pymilvus/milvus_client/async_milvus_client.py
  pymilvus/milvus_client/milvus_client.py
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed, PR | cherry-picked to 2.x

#2808 enhance: Multiple Cherry picks from master
  pymilvus/client/async_grpc_handler.py
  pymilvus/client/search_result.py
  pymilvus/orm/connections.py
  tests/test_collection.py
  tests/test_connections.py
  tests/test_search_result.py
Labels: approved, lgtm, size/M, ci-passed, dco-passed

#2826 fix: [cp25]Revert keep_alive default True
  pymilvus/orm/connections.py
Labels: approved, lgtm, size/XS, ci-passed, dco-passed
